### ISSUE TITLE
0.2 breaking changes questions

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#100]
Today I updated from the last 0.1 beta and found my raml project completely unable to build.

Primarily it seems to be complaining about `unknown` types, however all these types are defined ( I triple check this) `inheriting from unknown type`.

Furthermore it seems to complain when I use an inline array definition more than once `recurrent array type definition`.

I looked into the RC2 of RAML, but theres no indication of changes that would affect me.

**Comment by sichvoge** [comment]
Can you post a gist of your RAML. Let's have a look; as in the release notes indicated - the current parser already contains changes to the type system for RC2. The rules around validation have been changed that could effect your file.

There are tickets waiting to get merged into the spec (content and clarity is being discussed right now) that this version already implements.

**Comment by SimonSchick** [comment]
Isn't it a little optimistic to implement changes that haven't been merged into the spec yet?

Either way, my current RAML project is too large to post it in a gist (without making it completely unreadable).

I'll try to boil down the scenario:

The basic file structure:
```
doc/raml
├── endpoints
│   └── announcements.raml
├── index.raml
└── types
    ├── Announcement.raml
    └── index.raml
```

Reduced index.raml:

```yaml
#%RAML 1.0
title: XXXXXXXX
version: 1
baseUri: XXXXXX
protocols: [ HTTPS ]
mediaType: application/json
traits: !include traits/index.raml
types: !include types/index.raml
/announcements: !include endpoints/announcements.raml
```

types/announcement.raml:

```yaml
#%RAML 1.0
type: object
properties:
    text:
        description: The text of of the announcement.
        type: string
    script:
        description: A java-script to be executed on the browsers.
        type: string
    scope:
        description: Unknown.
        type: object
```

endpoints/announcements.raml:

```yaml
#%RAML 1.0
post:
    body:
        type: Announcement # uncommenting this line hides the error, the type seems to not be resolved.
    description: Creates a global announcement.
    responses:
        200:
            body:
                type: string
```
