### ISSUE TITLE
Examples only seem to support simple types/scalars

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#105]
This does not work, it apparently expects all values to be strings for some reason:

```yaml
#%RAML 1.0
description: An ingest definition.
type: object
properties:
    name:
        description: The name and location of the ingest.
        type: string
    host:
        description: Url of the host.
        type: string
    pingTest:
        description: A websocket address that is used for ping tests.
        type: string
    protocols:
        description: List of supported protocols
        type: array
        items:
            type: object
            properties:
                type:
                    type: string
                    enum: [ ftl, rtmp ]
                    description: The protocol name.
example:
    name: "Dallas, TX"
    host: "ingest-dal.beam.pro"
    pingTest: "ingest-dal.beam.pro"
    protocols: # this does not work, it expects a string here
        -
            type: "ftl"
        -
            type: "rtmp"
```

**Comment by sichvoge** [comment]
What is your error message? 

It seems you are trying to define a RAML Data type using typed fragment. But you are only saying `#%RAML 1.0`. If you want to use typed fragments to define a RAML type you need to use `#%RAML 1.0 DataType`. I changed that line and I don't have any problems anymore.

**Comment by SimonSchick** [comment]
So I changed it as you suggested:

```yaml
#%RAML 1.0 DataType
description: An ingest definition.
type: object
properties:
    name:
        description: The name and location of the ingest.
        type: string
    host:
        description: Url of the host.
        type: string
    pingTest:
        description: A websocket address that is used for ping tests.
        type: string
    protocols:
        description: List of supported protocols
        type: array
        items:
            type: object
            properties:
                type:
                    type: string
                    enum: [ ftl, rtmp ]
                    description: The protocol name.
example:
    name: "US: Dallas, TX"
    host: "ingest-dal.beam.pro"
    pingTest: "ingest-dal.beam.pro"
    protocols:
        -
            type: "ftl"
        -
            type: "rtmp"
```

Result is:

```javascript
{ code: 7,
  message: 'string is expected types/Ingest.raml',
  path: 'index.raml',
  start: 1624,
  end: 1629,
  line: 39,
  column: 0,
  range:
   [ { line: 39, column: 0, position: 1624 },
     { line: 39, column: 5, position: 1629 } ],
  isWarning: true }
```
