### ISSUE TITLE
types are getting parsed as a whole, not individually anymore

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#117]
Using the following RAML:

```yaml
#%RAML 1.0
title: API

types:
  TypeA:
    type: object
    properties:
      a: string[]
  TypeB:
    type: object
    properties:
      b:
        type: string[]
  TypeC:
    type: object
    properties:
      d:
        type: array
        items:
          type: string
  TypeE:
    type: string[]
  TypeF:
    type: array
    items:
      type: string
```

everything seems to be fine when you validate the complete RAML file. As soon as you look at each node and calling `node.errors()` I am getting error messages that `string[]` is not recognized. It seems that the behaviour of the parser validating the RAML as a whole interferes with `errors()` method which validates each node separately.
