### ISSUE TITLE
instance validation does not work with non required properties

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#119]
RAML:

```yaml
#%RAML 1.0
mediaType: application/json
title: Test RAML

types:
  base:
    description: base class
    type: object
    properties:
      extensions:
        type: string[]
        required: false
  myType:
    type: base
    properties:
      myProperty:
        type: string
        required: true
    example:
      {
        "myProperty" : "somevalue"
      }
```

The error message that I get is that the required property 'extensions' is missing inside my example. Obviously the property is not required.

Using the `?` the error disappears magically.

```yaml
#%RAML 1.0
mediaType: application/json
title: Test RAML

types:
  base:
    description: base class
    type: object
    properties:
      extensions?: string[]
  myType:
    type: base
    properties:
      myProperty:
        type: string
        required: true
    example:
      {
        "myProperty" : "somevalue"
      }
```

According to http://forums.raml.org/t/api-workbench-0-8-24-horribly-broken/1293; that worked fine in the previous version that did not have the new changes.
