### ISSUE TITLE
expanding resource type parameter does not work as expected

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#120]
Seems the parser does not correctly expand or resolute parameters declared in resource types. For example:

```yaml
resourceTypes:
  - item:
      description: Entity representing a <<resourcePathName|!singularize>>

/documents/{id}:
  type: item
```

The parser output using that with 0.8 or 1.0 is the following for the description of the `/documents/{id}` resource: "Entity representing a id". The expected value should be "Entity representing a document".

URI parameters should not be considered!
