### ISSUE TITLE
Print AST details for optional properties using `?` ends in the same AST than using no `?`

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#121]
RAML:

```yaml
types:
  base:
    description: base class
    type: object
    properties:
      extensions?: string[]
```

Currently prints out the following:

```
ObjectTypeDeclaration[TypeDeclaration] <--- types
		name : StringType[StringType]  =  base
		description : MarkdownString[MarkdownString]  =  base class
		type : StringType[StringType]  =  object
		ArrayTypeDeclaration[TypeDeclaration] <--- properties
			name : StringType[StringType]  =  extensions
			type : StringType[StringType]  =  string[]
```

Changing extensions to be required by removing the question mark ends in the exact same print. This is a bit confusing. @petrochenko-pavel-a confirmed that might only be a problem of the print method, not the actual AST.
