### ISSUE TITLE
Async load of overlay requires sync access

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#122]
Steps:

Create the following files:

raml1.raml:
```
#%RAML 1.0
title: Book Library API
documentation:
  - title: Introduction
    content: Automated access to books
  - title: Licensing
    content: Please respect copyrights on our books.
/books:
  description: The collection of library books
  get:
```

raml2.raml:
```
#%RAML 1.0 Overlay
usage: Spanish localization
masterRef: raml1.raml
documentation:
  - title: Introducción
    content: El acceso automatizado a los libros
  - title: Licencias
    content: Por favor respeta los derechos de autor de los libros
/books:
  description: La colección de libros de la biblioteca
```

test.js:
```
'use strict';

var fs       = require('fs');
var bluebird = require('bluebird');
var parser   = require('raml-1-parser');

parser.loadApi('raml2.raml', {
  rejectOnErrors: true,
  fsResolver:        {
    contentAsync: contentAsyncFn
  }
})
  .then(function (res) {
    res.expand();
    console.log('%j', res.toJSON());
  })
  .catch(function (error) {
    console.error(error);
  })
;

function contentAsyncFn(path) {
  return bluebird.resolve(fs.readFileSync(path, 'utf8'));
}
```

The JS test execution fails mentioning the absence of synchronous version of content method in fsResolver, though having an asynchronous version should be enough.

Note: it is important, that overlay/extension is set as first argument of loadApi method (in other words, parser does not know that the file is overlay and does not know its master beforehands).
