### ISSUE TITLE
multipleOf facet is not working

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#128]
RAML
```
types:
  Weight:
    type: number
    minimum: 3
    maximum: 5
    format: int64
    multipleOf: 4
```

fails with error `unknown facet: multipleOf`
