### ISSUE TITLE
`example` and `default` do not handle enum references

### ISSUE THREAD

**Issue by rocketraman** [raml-org/raml-js-parser-2#135]
Another new issue I found in recent versions of API workbench:

When an enum is defined by reference, `example` and `default` do not validate:

e.g.

```
SomeType:
    properties:
        anEnum:
            &someTypeEnum [ FOO, BAR, BAZ ]

/someresource:
    get:
        queryParameters:
            aParam:
                enum: *someTypeEnum
                default: [ FOO ]
                example: [ FOO, BAR ]
```

Neither of the `default` or `example` lines validate. I have only tested this in `queryParameters` -- its likely other clauses will fail in the same way.
