### ISSUE TITLE
Library ast JSON representation missing displayName attribute in types

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#139]
RAML
```
#%RAML 1.0 Library
# This file is located at libraries/file-type.raml
types:
  File:
    properties:
      name:
      length:
        type: integer
```

output:
```
"types": [
        {
          "File": {
            "name": "File",
            "properties": {
              "name": {
                "name": "name"
              },
              "length": {
                "name": "length",
                "type": [
                  "integer"
                ]
              }
            }
          }
        }
      ]
```

Code:
```
api.uses().forEach(function (usesItem) {
                var libraryAST = usesItem.ast();
                libraryAST = libraryAST.expand ? libraryAST.expand() : libraryAST;
                apiJSON.uses[usesItem.key()] = libraryAST.toJSON();
              });
