### ISSUE TITLE
Validation should check if the value provided to a specific node has the correct type.

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#147]
Using the following example:

```yaml
#%RAML 1.0
title: World Music API
baseUri: http://example.api.com/{version}
version: v1

/emails:
  - get:
  - post:
```

The parser returns `Unknown node` for `- get` and `- post`. What I actually expect here is that the parser tells me that the value of a resource must be a map. 

In general the validation should check if the value of a specific node conforms to its type defined in the RAML definition. For example, if a node is a string, or more commonly map / sequence.
