### ISSUE TITLE
RAML 0.8 example property shouldn't be parsed as JSON and have consistent behavior with XML

### ISSUE THREAD

**Issue by xaka** [raml-org/raml-js-parser-2#149]
RAML (XML):

```
#%RAML 1.0
title: Foo Bar
/users:
  post:
    body:
      application/xml:
        example: |
          <root></root>
```

Output (example is a string as in RAML, correct):

```
...
"example": "<root></root>\n",
...
```

-

RAML (JSON):

```
#%RAML 1.0
title: Foo Bar
/users:
  post:
    body:
      application/json:
        example: |
          [1,2,3,4,5]
```

Output (example is an array, not a string, incorrect):

```
...
"example": [
  1,
  2,
  3,
  4,
  5
],
...
```

-

RAML (XML, but example is JSON-like):

```
#%RAML 1.0
title: Foo Bar
/users:
  post:
    body:
      application/xml:
        example: |
          [1,2,3,4,5]
```

Output (example is an array, not a string, incorrect):

```
...
"example": [
  1,
  2,
  3,
  4,
  5
],
...
```

Issues:
- broken backward compatibility with RAML 0.8 output
- inconsistent behavior between JSON and non-JSON examples
- application/xml examples are still being treated as JSON whenever possible

Proposals:
- never apply any transformations for RAML 0.8 example properties and keep it as is i.e. string; RAML 0.8 doesn't allow example to have structured type anyway, only basic (integer, string, etc.)
