### ISSUE TITLE
Fix JSON External type facets test 4

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#155]
RAML

```
#%RAML 1.0
title: "test"

annotationTypes:
  TestAnnotation: string

types:
  SchemaType:
    type: !include ./scheme.json
    facets:
      TestFacet: string

```

should be invalid.
