### ISSUE TITLE
Fix JSON External type facets test 7

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#156]
RAML

```
#%RAML 1.0
title: "test"

annotationTypes:
  TestAnnotation: !include ./scheme.json

types:
  SchemaType:
    type: !include ./scheme.json
    displayName: test
    (TestAnnotation):
      name: "sdfdsf"
  TestType:
    type: SchemaType

```

should be invalid
