### ISSUE TITLE
Fix JSON External type facets test 12

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#158]
RAML

```
#%RAML 1.0
title: "test"

annotationTypes:
  TestAnnotation: !include ./scheme.json

types:
  SchemaType:
    type: !include ./scheme.json
    displayName: test
    (TestAnnotation):
      name: "sdfdsf"
  TestType:
    type: object
  TestType2:
    type: object
    properties:
      testProp:
        type: SchemaType
        description: test

```

should be invalid.
