### ISSUE TITLE
Fix JSON External type facets test 17

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#161]
RAML

```
#%RAML 1.0
title: "test"

annotationTypes:
  TestAnnotation: !include ./scheme.json

types:
  SchemaType:
    type: !include ./scheme.json
    displayName: test
    (TestAnnotation):
      name: "sdfdsf"
  TestType:
    type: object
  TestType2:
    type: object
    properties:
      testProp:
        type: !include ./scheme.json
        properties:
          name: string

```

is invalid, but instead of "property testProp range type has error: specifying unknown facet: properties" should say something like "It is not allowed to use external types in property definitions"
