### ISSUE TITLE
Header properties are returned as not required by default

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#170]
RAML:
```
#%RAML 1.0
title: Headers
version: 1.0

/orders:
  displayName: Orders
  description: Orders collection resource used to create new orders.
  post:
    headers:
      hola: string
    body:
      application/json:
        type: object
        properties:
          temp: string
```

Output:
```
{
  "title": "Headers",
  "version": "1.0",
  "resources": [
    {
      "methods": [
        {
          "headers": {
            "hola": {
              "name": "hola",
              "displayName": "hola",
              "type": [
                "string"
              ],
              "repeat": false,
              "required": false
            }
          },
          "body": {
            "application/json": {
              "name": "application/json",
              "displayName": "application/json",
              "type": [
                "object"
              ],
              "repeat": false,
              "required": true,
              "properties": {
                "temp": {
                  "name": "temp",
                  "displayName": "temp",
                  "type": [
                    "string"
                  ],
                  "repeat": false,
                  "required": true
                }
              }
            }
          },
          "method": "post"
        }
      ],
      "description": "Orders collection resource used to create new orders.",
      "relativeUri": "/orders",
      "displayName": "Orders",
      "relativeUriPathSegments": [
        "orders"
      ]
    }
  ]
```
