### ISSUE TITLE
Using extensions, types included in libraries in the extended RAML are missing properties

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#172]
Parsing extensions.raml
```
#%RAML 1.0 Extension
usage: The location of the public instance of the Piedmont library API
extends: mini-library.raml
baseUri: http://new
```

mini-library.raml
```
#%RAML 1.0
title: API with Library
version: 1

uses:
  library: libraries/type.raml

/test:
  post:
    body:
      application/json:
        type: library.Type
````

libraries/type.raml
```
#%RAML 1.0 Library
# This file is located at libraries/type.raml

types:
  Type:
    properties:
      one: string
```

When accessing the included Library AST and converting to JSON, seems like some defaults are missing. Calling:
```
 api.uses().forEach(function (usesItem) {
              var libraryAST = usesItem.ast();
              libraryAST = libraryAST.expand ? libraryAST.expand() : libraryAST;
              var libraryJSON = libraryAST.toJSON();
});
```

returns in libraryJSON:
```
{
  "types": [
    {
      "Type": {
        "name": "Type",
        "properties": {
          "one": {
            "name": "one",
            "type": [
              "string"
            ]
          }
        }
      }
    }
  ]
}
```
