### ISSUE TITLE
parser does not complain when using string as a value for securedBy

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#176]
According to the RAML 0.8 spec

> The value of the securedBy attribute MUST be a list of any of the security schemes defined in the securitySchemes declaration.

Using the following example:

```yaml
#%RAML 0.8
title: djkgdg

securitySchemes:
  - test:
      type: Basic Authentication

/protected:
  securedBy: test
```

The parser does not complain!
