### ISSUE TITLE
Strange validation on annotations

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#211]
I have the following example:

```yaml
#%RAML 1.0
title: Test

types:
  dateTime:
    type: datetime
    format: rfc2616
    example: Mon, 31 Oct 2016 00:00:00 GMT

annotationTypes:
  planned: dateTime

/products:
  (planned): Mon, 31 Oct 2016 00:00:00 GMT
```

The example in the type does not throw any issue, but the annotation `(planned)` does complaining its not valid `rfc3339`. How can that be since I use `format: rfc2616`?

![image](https://cloud.githubusercontent.com/assets/498114/15355503/09819cb6-1ceb-11e6-979d-e365a549e457.png)

That also happens using latest parser version: 0.2.12
