### ISSUE TITLE
Problem updating from 0.2.10 to 0.2.20

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#232]
My problem is as follows:

I have a type that has special keys that look like this:

```json
{
   "my:special:key": "someValue"
}
```

So I had a type like this:

```YML
#%RAML 1.0
type: object
properties:
    "my:special:key"?:
        type: string
        description: Some description
```

when updating to 0.2.20 I got the following error: `properties should be a map`

Now I assumed that suffixing the thing with the ? was wrong and it just happened to work like that before, so I updated it and moved the ? into the key eg:

```YML
#%RAML 1.0
type: object
properties:
    "my:special:key?":
        type: string
        description: Some description
```

But then I get the error: `property my:special:key range type has error:specifying unknown facet:descripton`.

So what is the correct way to add properties that have irregular characters in them?

PS: Please fix !include traces!
