### ISSUE TITLE
Cannot use YAML files with !include for endpoint example

### ISSUE THREAD

**Issue by nanovazquez** [raml-org/raml-js-parser-2#249]
### Scenario
I have defined a set of resources with their corresponding response examples inline in the `api.raml` file. 
I want to move the response example of one of my endpoints to a different file (and reference it via `!includes`).

### Problem
When moving the example to a different YAML file I receive the following error in the API Designer.

![image](https://cloud.githubusercontent.com/assets/1306634/15652643/099ca282-265e-11e6-90ff-74540ae9240f.png)

If we use the parser directly (thanks @juancoen!), we receive the following error:

```json
{
  "parserErrors": [
    {
      "code": 11,
      "message": "object is expected",
      "path": "api.raml",
      "start": 281,
      "end": 288,
      "line": 14,
      "column": 10,
      "range": [
        {
          "line": 14,
          "column": 10,
          "position": 281
        },
        {
          "line": 14,
          "column": 17,
          "position": 288
        }
      ],
      "isWarning": false
    }
  ]
}
```

### Workaround
Convert the example payload to JSON.

![image](https://cloud.githubusercontent.com/assets/1306634/15652884/b99a9314-265f-11e6-88e6-087e257d123c.png)

### Resources

**api.raml**
```yaml
#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/042017e5-4a4e-45ec-ba49-738ad7f2ffcf
title: Mulesoft Info
version: 1
uses:
  Types: types.raml
mediaType: application/json

/features:
  get:
    responses:  
      200:
        body:
          type: Types.Feature[]
          example: !include examples/features.yaml
```

**types.raml**
```yaml
#%RAML 1.0 Library
types:
  url:
    type: string
    pattern: (https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})
  Feature:
    type: object
    properties:
      id: number
      title: string
      description?: string
      pic: url
```

**examples/features.yaml**
```yaml
- 
  id: 1
  title: "feature1"
  description: "description of feature 1"
  pic: "http://naw.netatwork.netdna-cdn.com/uploads/2015/06/icon-security-monitoring.png"
- 
  id: 2
  title: "feature2"
  description: "description of feature 2"
  pic: "http://naw.netatwork.netdna-cdn.com/uploads/2015/06/icon-security-monitoring.png"
- 
  id: 3
  title: "feature3"
  description: "description of feature 3"
  pic: "http://naw.netatwork.netdna-cdn.com/uploads/2015/06/icon-security-monitoring.png"
- 
  id: 4
  title: "feature4"
  description: "description of feature 4"
  pic: "http://naw.netatwork.netdna-cdn.com/uploads/2015/06/icon-security-monitoring.png"
- 
  id: 5
  title: "feature5"
  description: "description of feature 4"
  pic: "http://naw.netatwork.netdna-cdn.com/uploads/2015/06/icon-security-monitoring.png"
```
