### ISSUE TITLE
Strange behaviour when including an empty file

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#254]
Assume the following RAML:

``` yaml
#%RAML 1.0
title: GitHub API
version: v3
baseUri: https://api.github.com
mediaType:  application/json

types:
  Gist:  !include types/gist.raml
  Gists: !include types/gists.raml
resourceTypes:
  collection: !include types/collection.raml
```

The files gist.raml, gists.raml, and collection.raml are all empty (except the `#%RAML 1.0 <fragment>` first line). I don't get any errors on the types section, but I do on resourceTypes where the parser complains about that the node collection can not be a scalar. Everything should behave exactly the same and there shouldn't be any problems with the empty files.
