### ISSUE TITLE
empty value in a string valued node should not be allowed as per spec

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#258]
The spec states the following:

> In the following example, the type of an object and has two required properties, name and comment, both defaulting to type string. In example, name is assigned a string value, but comment is null and this is not allowed because RAML expects a string.

And this is the example below this quote:

```yaml
types:
  NullValue:
    type: object
    properties:
      name:
      comment:
    example:
      name: Fred
      comment: # Providing no value here is not allowed.
```

The parser does not complain here which is obviously against what the spec says.
