### ISSUE TITLE
Facets dropped from JSON when inheriting from multiple number types

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#268]
Should throw an error or support it, at the moment it silently drop maximum, minimum from Bar when calling toJSON on the ast. removing `integer|` it works as expected.

```
types:
  Foo:
    type: integer|number
  Bar:
    type: Foo
    maximum: 2
    minimum: 1
```
