### ISSUE TITLE
Examples for number[] does not validate with `resourceTypes` defined

### ISSUE THREAD

**Issue by rocketraman** [raml-org/raml-js-parser-2#272]
Similar to #134 , a `number[]` with `0` does not validate (using api workbench 0.8.31 and parser 0.2.24):

Does not validate:

```
  GeoPoint:
    properties:
      coordinates:
        type: number[]
    example:
      coordinates: [100.0, 0.0]
```

but does validate:

```
  GeoPoint:
    properties:
      coordinates:
        type: number[]
    example:
      coordinates: [100.0, 1.0]
```
