### ISSUE TITLE
Object types with parametrized supertype provide properties in a strange manner.

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#288]
Instead of being provided by **properties** field, the properties are provided by **fixedFacets** field.

Example:
```
traits:
  tr:
    body:
      application/json:
        type: <<param>>
        properties:
          p1:
```
resulting JSON:
```
{
  "traits": {
    "tr": {
      "body": {
        "application/json": {
          "name": "application/json",
          "displayName": "application/json",
          "type": ["<<param>>"],
          "fixedFacets": {
            "properties": {
              "prop": "string"
            }
          }
        }
      }
    }
  }
}
```
