### ISSUE TITLE
For array examples structured representation is incorrect in JSON

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#296]
```
  SomeType:
    type: string[]
    example:
      - some string
      - another string
```
```
"structuredExample": {
            "value": [
              "some string",
              "another string"
            ],
            "strict": true,
            "name": null,
            "structuredValue": {
              "undefined": "another string"
            }
          }
```

So, `structuredValue` here is
```
{
  "undefined": "another string"
}
```
which is incorrect
