### ISSUE TITLE
Additional Properties must be allowed

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#302]
As spec says:
**Additional properties:**
By default, any instance of an object can have additional properties beyond those specified in its data type properties facet

**Annotations**: 
An annotation type declaration has the same syntax as a data type declaration, and its facets have the same syntax as the corresponding ones for data types, but with the addition of the allowedTargets facet

Using the following RAML

```yaml
#%RAML 1.0
title: New API
version: v1
baseUri: http://api.samplehost.com
types:
  Point:
    type: object
    properties:
      x: number
      y: number
annotationTypes:
  Label:
    properties:
      point: Point[]
/resource:
  (Label):
      point:
        -
          x: 4
          y: 3
        -
          x: 3
          y: 1
          z: 3
```

Actual Result: 
- The expected result of the TCK test case is wrong. It expected that Z is not allowed
- JS parser does not allow additional properties

Expected result:
Z must be accepted as an additional property
Test must be changed
