### ISSUE TITLE
Using '[]:' to define a property is not allowed

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#304]
Parsing the following RAML:
```yaml
#%RAML 1.0
title: Annotation with arbitrary properties
annotationTypes:
  suborg:
    type: object
    properties:
      prop1: number
      []: object
/assets:
  (suborg):
        prop1: 4
        manager:
          name: Tom
        superintendent:
          name: Bob
        role:
          roleName: admin
```
Actual result:

JS parser allows to define a property with []: or [] with a regex. It is not clear if it is used as a pattern, to restrict a property name

Expected result: It is not allowed to use []:
