### ISSUE TITLE
[TCK] TC0027 Annotations: Values are not correctly validated against pattern defined

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#305]
Parsing the following RAML:

```yaml
#%RAML 1.0
title: TCK Sample. RAML 1.0 Annotations 001.
version: v1
baseUri: http://api.samplehost.com/{version}
annotationTypes:

  simpleAnnotation:
    minLength: 8
    maxLength: 64
    pattern: "[a-zA-Z0-9]{8,32}"

  objectAnnotation:
    properties:
      property1:
        properties:
          field1?:
          field2:
            type:  number
      property2?:

types:
  MyType:
    (simpleAnnotation): simpleAnnotation_value_on_type
    (objectAnnotation):
      property1:
        field1: field1_value
        field2: 15
      property2: baseProperty2_value

/helloWorld:
  get:
    (simpleAnnotation): simpleAnnotation_value_on_method
    (objectAnnotation):
      property1:
        field2: 19
```
**Actual result:**

The RAML is parsed successfully

**Expected result:**

As the value of SimpleAnnotation is restricted to: a-zA-Z0-9

simpleAnnotation_value_on_method value is not valid

JS parser should fail showing the corresponding message
