### ISSUE TITLE
[TCK] TC029 - Annotations: Parameter inside annotations must be allowed

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#306]
Parsing the folowing raml:

```yaml
#%RAML 1.0
title: TCK Sample. RAML 1.0 Annotations 001.
version: v1
baseUri: http://api.samplehost.com/{version}
resourceTypes:
  rt1:
    get:
      (<<annotation>>): simpleAnnotationValue
      (objectAnnotation):
        property1:
          field1: <<annotationField>>
          field2: 15
        property2: baseProperty2_value
      
annotationTypes:

  simpleAnnotation:
    minLength: 8
    maxLength: 64
    pattern: "[a-zA-Z0-9]{8,32}"

  objectAnnotation:
    properties:
      property1:
        properties:
          field1?:
          field2:
            type:  number
      property2?:
/resource:
  type: { rt1: { annotation: simpleAnnotation, annotationField: someFieldValue } }
```

**Actual result:** 
TCK test expected an error when using a parameter inside an annotation as follows:
"(<<annotation>>):" 

JS parser displays an error

**Expected result:**
- Parameters inside an annotation must be allowed  by JS parser
- Modify Test
