### ISSUE TITLE
'-' before a name of a key is not allowed

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#307]
Parsing the following RAML

```yaml
#%RAML 1.0
title: Test
baseUri: http://{a}.myapi.org
baseUriParameters:
  a:
    - displayName: second
      description: This is A
      type: string
    - displayName: 2
      description: This is A
      type: integer
```
**Actual result:**
JS parser allows to use '-' before a name of a key

**Expected result:**
JS parser must not allow to use '-' before the name of a key
