### ISSUE TITLE
baseUriParameter usage is incorrectly validated

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#309]
```yaml
#%RAML 1.0
title: Test
baseUri: http://{a}.myapi.org
baseUriParameters:
  b:
    displayName: second
    description: This is A
    type: string
```

**Actual result:** 
JS parser displays an error saying that baseUriParameter is declared but not used

**Expected result:** 

JS parser must not validate whether a baseUriParameter is used or not
In case it is needed to display something, it should be a warning or at tooling level
