### ISSUE TITLE
Example: Repeat usage is not defined in the spec but is implemented

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#310]
```yaml
#%RAML 1.0
title: Test API

/resource:
  get:
    queryParameters:
      param1:
        type: number
        repeat: true
        example: 2

```

**Actual result:**
Repeat facet is implemented as valid

**Expected result:**
It is not defined how to use it in the spec. How is the usage in JS parser?
