### ISSUE TITLE
Examples: Is not allowed to pass only one value to an array

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#311]
```yaml
#%RAML 1.0
title: Test named parameters
types:
  dept_code:
    pattern: ^\d+\-\w+$

traits:
  chargeable:
    headers:
      X-Dept:
        type: dept_code[]
        examples:
          one_dept:
            strict: true
            content:
              - X-Dept: 230-OCTO
```

**Actual result:**

 "parserErrors": [
    {
      "code": 11,
      "message": "array is expected",
      "path": "discriminator-3.raml",
      "start": 188,
      "end": 196,
      "line": 12,
      "column": 10,
      "range": [
        {
          "line": 12,
          "column": 10,
          "position": 188
        },
        {
          "line": 12,
          "column": 18,
          "position": 196
        }
      ],
      "isWarning": false
    }
  ]
}

**Expected result:**
It must be allowed to pass only one value to an array

**Comment by KonstantinSviridov** [comment]
As per spec, "The actual example of a type instance" goes under the `value` key. Thus, the correct way to define a one-element array example is
```
        examples:
          one_dept:
            strict: true
            value:
              - X-Dept: 230-OCTO
```

**Comment by sichvoge** [comment]
Even the example seems to be wrong, shouldn't it be:

```yaml
#%RAML 1.0
title: Test named parameters
types:
  dept_code:
    pattern: ^\d+\-\w+$

traits:
  chargeable:
    headers:
      X-Dept:
        type: dept_code[]
        examples:
          one_dept:
            strict: true
            value:
              - 230-OCTO
```
