### ISSUE TITLE
mime/type: should be supported as media type

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#314]
Parsing the following RAML:
```yaml
#%RAML 1.0
title: test
/test:
  post:
    body:
      application/json:
      application/vnd.xara:
      audio/EVRCB:
      audio/vnd.dts:
      image/tiff:
      message/global:
      model/vnd.moml+xml:
      multipart/voice-message:
      text/turtle:
      video/JPEG:
      mime/type:
```

**Actual result:**
mime/type: is not supported
JS parser says is not a valid media type

**Expected result:**
'mime/type:' is equal to mime/type: any and must be supported
