### ISSUE TITLE
Modify error message when array has incorrect element types

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#317]
```yaml
#%RAML 1.0
title: API

types:
  SimpleUnion:
    type: string[] | number[]

  TypeWithUnionProps:
    type: object
    properties:
      unionArray1: SimpleUnion
      unionArray2: SimpleUnion
    example:
      unionArray1: [3, 2, prueba]
      unionArray2: [blah, blah, blah]
```
**Actual result**
"string is expected"

**Expected result:**
The message always says that string is expected, no matter if the array expect bot number or string
