### ISSUE TITLE
unresolved reference using annotation type with type null

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#327]
The parser cannot resolve the `deprecated` annotation. It seems that it is only when the type is `null`. Any other type and even the following union `null | string` works.

```yaml
#%RAML 1.0
title: Illustrating annotations

annotationTypes:
  deprecated: null
/users:
  get:
    (deprecated):
```
