### ISSUE TITLE
bug in validating examples from a fragment file

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#333]
This is related to my observations in #332 but I attach a fixed version here to show when the error appears.

It seems that the parser validates an example differently when its inlined vs an external fragment.

```yaml
#%RAML 1.0
title: Customer API
version: 1.0

mediaType: application/json
types:
  Customer: !include types/customer.raml
  Message: !include types/message.raml

/customer:
  post:
    description: |
      Create a new Customer
    body:
      type: Customer
      example: !include examples/customer.raml
```

This throws the error that I observed in #332. Copy & paste the content (expand) from the example file fragment the error disappears. How can that happen when validate on top of the expanded version anyways?

```yaml
#%RAML 1.0
title: Customer API
version: 1.0

mediaType: application/json
types:
  Customer: !include types/customer.raml
  Message: !include types/message.raml

/customer:
  post:
    description: |
      Create a new Customer
    body:
      type: Customer
      example:
        sourceSystem: Salesforce A
        customerId: "1"
        mdmId: a1
        customerType: Residential
        customerName: Roeder Consulting
        phoneNumbers:
          - type: Main
            phoneNumber: 404-447-6386
            preferred: yes
          - type: Home
            phoneNumber: 678-614-5006
        emails:
          - type: Corporate
            address: info@roederConsulting.com
            preferred: yes
        socialIds:
          - channel: facebook
            type: type1
            value: RoederConsulting
        addresses:
          - type: Headquarters
            street: 257 Stone Park Drive
            street2: #1
            city: Woodstock
            stateProvince: GA
            postalCode: "30188"
            countryCode: USA
            latitude: "32.00"
            longitude: "33.00"
        createDateTime: 2014-08-07T01:02:03
        lastModifiedDateTime: 2016-01-01T12:13:14
```
