### ISSUE TITLE
Parser should fail if two security schemes have the same name

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#34]
This RAML should fail with the new parser:
```
#%RAML 0.8
title: some API
securitySchemes:
  - scheme1:
      type: x-custom
  - scheme1:
      type: x-custom
```
