### ISSUE TITLE
The parser produces warning for miscorrespondence between parameter type and its default value type in RAML 0.8.

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#350]
In fact, it must produce an error, not warning.
Example situation:
```
#%RAML 0.8
title: test
/test:
  post:
    queryParameters:
      limit:
        type: integer
        default: someValue
```
