### ISSUE TITLE
parser wrongly complains on the AnnotationTypeDeclaration fragment about allowedTargets

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#358]
Parsing the following fragment:

```yaml
#%RAML 1.0 AnnotationTypeDeclaration

displayName: Method handler function path
allowedTargets: Method
properties:
  path:
    type: string
    description: |
      A string that is passed to the pathResolver function in order to return
      a route handler function.
    examples:
      example1:
        description: |
          A relative file that export a default function
        value: './folderrfolder/file.js'
      example2:
        description: |
          Dot separated path to method
        value: 'server.controllers.user.findUser'
  config?:
    type: object
    description: |
      Config object will be passed as the first parameter to the controller on every call
```

I get that the allowedTargets is not allowed here. As per spec it is.
