### ISSUE TITLE
anchors and references and misleading error ('inheriting from unknown type')

### ISSUE THREAD

**Issue by mpfau** [raml-org/raml-js-parser-2#359]
The following snippet triggers the error message 'inheriting from unknown type'. This message is only triggered, as long as YAML anchors and references are used.

``` yaml
#%RAML 1.0 Library
traits:
  headed:
    headers:
      X-TRACE-ID: &traceId
        type: string
        required: false
  headed-legacy:
    headers:
      X-TRACE-ID: *traceId
```

Full error output:

``` yaml
{
  "code": 11,
  "message": "inheriting from unknown type",
  "path": "anchor-bug.raml",
  "start": "5:8",
  "isWarning": false
}
```
