### ISSUE TITLE
RAML with duplicated type in Security Scheme fails in Workbench but not in the Parser

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#36]
This RAML:
```
#%RAML 0.8
title: some API
securitySchemes:
 - scheme1:
     type: x-custom
     type: x-custom-2
```
In Workbench:
![screen shot 2015-11-23 at 12 56 50 pm](https://cloud.githubusercontent.com/assets/1169708/11341571/c1583420-91e1-11e5-9018-bf6d0e803dfa.png)

The parser returns:
```
{
  "title": "some API",
  "securitySchemes": [
    {
      "scheme1": {
        "type": "x-custom"
      }
    }
  ]
}
```

And errors() returns an empty array
