### ISSUE TITLE
patternProperties is no longer supported in raml 1.0

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#363]
```yaml
#%RAML 1.0
title: My API With Types
types:
  Method:
    type: object
    properties:
      name:
        type: string
  Resource:
    type: object
    patternProperties:
      "post|get|put": Method
```

**Actual result:** 

```yaml
  "types": [
    {
      "Method": {
        "name": "Method",
        "displayName": "Method",
        "type": [
          "object"
        ],
        "repeat": false,
        "required": true,
        "properties": {
          "name": {
            "name": "name",
            "displayName": "name",
            "type": [
              "string"
            ],
            "repeat": false,
            "required": true
          }
        }
      }
    },
    {
      "Resource": {
        "name": "Resource",
        "displayName": "Resource",
        "type": [
          "object"
        ],
        "repeat": false,
        "required": true,
        "patternProperties": [
          {
            "name": "post|get|put",
            "displayName": "post|get|put",
            "type": [
              "Method"
            ],
            "repeat": false,
            "required": true
          }
        ]
      }
    }
  ],
  "title": "My API With Types"
}
```

**Expected result:**

patternProperties was supported in raml 0.8, but for raml 1.0 there is no longer support, it should be validated
