### ISSUE TITLE
Enum: is not allowed to set repeated values

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#366]
```yaml

#%RAML 1.0
title: Test
baseUri: http://{a}.myapi.org
baseUriParameters:
  a:
    displayName: A
    description: This is A
    minLength: 123
    enum: [ "value", "value2", "value2" ]

```

**Actual result:** 

                {"path":"api.raml","code":7,"line":2,"column":0,"range":[{"line":2,"column":0,"position":23},{"line":2,"column":7,"position":30}],"position":23,"message":"Invalid resource name: unmatched '{'"}

**Expected result:**

As spec says

An enum is An enumeration of all the possible values of instances of this type. The value is an **array** containing representations of these possible values; an instance of this type MUST be equal to one of these values.

So as it is an array it must allow repeated values
