### ISSUE TITLE
Libraries used by fragments

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#368]
1. Libraries used by fragment are not visible in API including the fragment
2. If it happens that name of library used by fragment conflicts with name of library used by main API, the template expansion procedure must resolve the conflict

**Comment by KonstantinSviridov** [comment]
Example:
```
#api.raml
#%RAML 1.0
title: Test API

resourceTypes:
  rt: !include ./fragments/rt.raml

/resource:
  type: rt
```
```
#fragments/rt.raml
#%RAML 1.0 ResourceType

uses:
  lib: ../libs/lib.raml

post:
  body:
    application/json: lib.MyType
```
```
libs/lib.raml
#%RAML 1.0 Library

types:
  MyType: object
```
result:
![usesfragments](https://cloud.githubusercontent.com/assets/6206034/17032327/16340852-4f92-11e6-8bf1-a8e669993699.png)
