### ISSUE TITLE
Invalid JSON is produced for Inlined type declarations

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#390]
Everithing is fine with inlined types which have a single field in their declaration. For example, the type below isdefined by `properties` field:
```
application/json:
        type:
          properties:
            p1: object
            p2: object
```
and the JOSN is
```
"application/json": {
                "name": "application/json",
                "displayName": "application/json",
                "required": true,
                "type": {
                  "name": "type",
                  "displayName": "type",
                  "type": [
                    "object"
                  ],
                  "required": true,
                  "properties": {
                    "p1": {
                      "name": "p1",
                      "displayName": "p1",
                      "type": [
                        "object"
                      ],
                      "required": true
                    },
                    "p2": {
                      "name": "p2",
                      "displayName": "p2",
                      "type": [
                        "object"
                      ],
                      "required": true
                  }
                }
```
At the same time if we add some more fields (`additionalProperties` in example below)
```
application/json:
        type:
          properties:
            p1: object
            p2: object
          additionalProperties: false
```
the resulting JSON is invalid:
```
"application/json": {
                "name": "application/json",
                "displayName": "application/json",
                "type": [
                  null,
                  "false"
                ]
              }
```
