### ISSUE TITLE
Introduce traces in the error section inside the parser output

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#394]
In some cases associating an error with particular position in code is not correct or inconvenient.

For example:
```
#%RAML 1.0
title: New API
types:
  TestType:
    type: object
    properties:
      prop1: number
    example: !include examples/example.raml
```
```
#examples/example.raml
prop1: stringValue
```
It's not correct to place error only in `example.raml line 1`, because it's validity depends on type using it.

Placing a single error on the  `example: !include examples/example.raml` line is not handy for the user, as he might expect more details.

In such cases Workbench provides error trace:
![trace2](https://cloud.githubusercontent.com/assets/6206034/16703245/4a710096-4585-11e6-800c-5f41b1944464.png)

The suggestion is to introduce trace information into TCK JSON. For the example:

```
"errors": [
    {
      "code": 11,
      "message": "number is expected",
      "path": "api.raml",
      "line": 7,
      "column": 4,
      "position": 102,
      "range": [
        {
          "line": 7,
          "column": 4,
          "position": 102
        },
        {
          "line": 7,
          "column": 11,
          "position": 109
        }
      ],
      "trace": [
        {
          "code": 11,
          "message": "number is expected",
          "path": "examples/example.raml",
          "line": 0,
          "column": 0,
          "position": 0,
          "range": [
            {
              "line": 0,
              "column": 0,
              "position": 0
            },
            {
              "line": 0,
              "column": 18,
              "position": 18
            }
          ]
        }
      ]
    }
  ]
```

In the example above you see that the reported error is on the api.raml file, but thats not true. The error occurs inside the "examples/example.raml" file and therefore the order would need to be reversed. 

An example:

```
#api.raml
#%RAML 1.0

title: test
resourceTypes:
  rt: !include resourceTypes/rt.raml

# resourceTypes/rt.raml
post:
  body:
    application/json:
      properties:
        p1: string
      example:
        p1: 5
```

Now the error does not have any trace, and it is

```
{
      "code": 11,
      "message": "string is expected",
      "path": "api.raml",
      "line": 4,
      "column": 2,
      "position": 45,
      "range": [
        {
          "line": 4,
          "column": 2,
          "position": 45
        },
        {
          "line": 4,
          "column": 4,
          "position": 47
        }
      ]
    }
```

With the reversed trace it is going to be

```
{
      "code": 11,
      "message": "string is expected",
      "path": "resourceTypes/rt.raml",
      "line": 6,
      "column": 8,
      "position": 102,
      "range": [
        {
          "line": 6,
          "column": 8,
          "position": 102
        },
        {
          "line": 6,
          "column": 10,
          "position": 104
        }
      ],
      "trace": [
        {
          "code": 11,
          "message": "string is expected",
          "path": "api.raml",
          "line": 4,
          "column": 2,
          "position": 45,
          "range": [
            {
              "line": 4,
              "column": 2,
              "position": 45
            },
            {
              "line": 4,
              "column": 4,
              "position": 47
            }
          ]
        }
      ]
    }
```

That makes it very clear what the primary error is.
