### ISSUE TITLE
Uses node cannot be overridden or added by an overlay

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#404]
```yaml

#%RAML 1.0 Overlay
title: Slave RAML
extends: master.raml
uses:
  decls: lib/decls.raml
    
/elements:
  get:
    description: |
      describing your method here
    #lets add some annotation
    (decls.important):
```

**Actual result:** 
No errors

**Expected results:**
Uses node cannot be added by an overlay
