### ISSUE TITLE
Security scheme type valdiation with overlay

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#409]
For this API the invalid security scheme type is reported:

```
#%RAML 1.0
title: hybrid-rest-services
version: 0.4
mediaType: application/json
securedBy: x-ttt
protocols: HTTP
securitySchemes:
   x-ttt:
      type: DigestSecurityScheme Authentication

baseUri: https://anypoint.mulesoft.com/hybrid/api/v1
traits:
   env-org-pair:
resourceTypes:
   servers-collection:
/servers:
  is: env-org-pair
  securedBy: x-ttt

```

But, when we apply the overlay:
```
#%RAML 1.0 Overlay
title: Extension
extends: api.raml
traits:
  env-org-pair:

```

The same error is missed.
