### ISSUE TITLE
Additional property with "any" key should not conflict with explicit properties

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#411]
```
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      //: # force all additional properties to be a string
        type: string
```

Here, JS parser reports a error regarding explicit properties (`name` and `age`) conflicting with the pattern property `//`, which basically matches any key.

While this situation may be a potential user's mistake, it is allowed by the spec. So this error should be replaced with a warning, and error message should be cleaned up.
