### ISSUE TITLE
Null items allowed in arrays

### ISSUE THREAD

**Issue by eduramiba** [raml-org/raml-js-parser-2#412]
I am trying to enforce array items to be required by the parser validation so the following example is treated as invalid. but it produces no errors:

```json
{
   "reports": [null]
}
```

I have tried this:

```yaml
Person:
    type: object
    required: true
     ...
Data:
    type: object
    properties:
      reports:
        type: Person[]
```

Is this a bug in the parser or actually not possible in RAML?

Version used 0.2.30
Thank you.
