### ISSUE TITLE
The error message "items should be unique" appears twice

### ISSUE THREAD

**Issue by fescobar** [raml-org/raml-js-parser-2#415]
When I create an array with unique items, the error message **"items should be unique"** appears twice.
![screen shot 2016-08-09 at 6 20 03 pm 2](https://cloud.githubusercontent.com/assets/1236418/17534126/15a0ece0-5e5e-11e6-9fa8-402e9fd7ce75.png)

```
#%RAML 1.0
title: API Animals & People
version: 1.7
baseUri: http://www.sa.uk
mediaType: [ application/json, application/xml ]

/flags:
  description: The collection of flags
  get:
    body:
      type: boolean[]
      minItems: 0
      maxItems: 3
      uniqueItems: true
      example: # example that contains array
        - false
        - true
        - false
```
