### ISSUE TITLE
When "uniqueItems" facet is false, appears error message "items should be unique".

### ISSUE THREAD

**Issue by fescobar** [raml-org/raml-js-parser-2#416]
When "uniqueItems" facet is false, appears error message "items should be unique". In this case the JS Parse shouldn't validate.

```
#%RAML 1.0
title: API Animals & People
version: 1.7
baseUri: http://www.sa.uk
mediaType: [ application/json, application/xml ]

/flags:
  description: The collection of flags
  get:
    body:
      type: boolean[]
      minItems: 0
      maxItems: 3
      uniqueItems: false
      example: # example that contains array
        - false
        - true
        - false
```
