### ISSUE TITLE
DateFormat is not validated

### ISSUE THREAD

**Issue by fescobar** [raml-org/raml-js-parser-2#419]
When format value is invalid, it doesn't appear an error message.

date-time: A timestamp in one of the following formats: if the format is omitted or set to rfc3339, uses the "date-time" notation of RFC3339; if format is set to rfc2616, uses the format defined in RFC2616.

```
#%RAML 1.0
title: API Animals & People
version: 1.7
baseUri: http://www.sa.uk
mediaType: [ application/json, application/xml ]

types:
  Email:
    type: object
    properties:
      created:
        type: datetime
        format: anytype
        example: 1985-04-12T23:20:50.52Z
```

![dateformat is not validated](https://cloud.githubusercontent.com/assets/1236418/17559407/8451461c-5ef4-11e6-830b-8e4b1e553508.png)
