### ISSUE TITLE
js parser should return warnings instead of errors

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#421]
Hi,

After updating my JS parser version from v0.2.26 to the newest v0.2.31 I am getting a lot of errors that has been reported as warnings before. As discussed previously, for compatibility reasons, we switched errors to warnings for any 0.8 specs in the following scenarios: 

1. is the example valid JSON/XML
2. does the example conform against its schema

We need to fix that as soon as possible, and also add appropriated tests to avoid any future regressions on that.

Thanks!

Appendix Example:

```yaml
#%RAML 0.8
title: My API

/single-query-record/{code}:
  uriParameters:
    code:
      displayName: code
      type: string
      required: false
      repeat: false
  post:
    queryParameters:
      query...:
        displayName: query...
        description: Hello
        type: string
        required: true
        example: |
          {
            "bankNo": "666666666666666666"
          }
```
