### ISSUE TITLE
Templates expand issue with explicit overlay chains.

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#424]
Consider a master API and overlay:
```
#%RAML 1.0
title: t
traits:
  tr:
    queryParameters:
      q:
/resource:
  get:
    is: [ tr ]
```
```
#%RAML 1.0 Overlay
extends: api.raml
```
amd load them as
```
raml1Parser.loadApi("api.raml",["overlay.raml"])
```
The `get: /resource` method of the resulting RAML spec does not have any query parameters disregarding whether we call `exapand()` or not.
