### ISSUE TITLE
Not very helpful error message

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#427]
See the following example:

``` yaml
#%RAML 1.0
title: Sample API
version: v0
baseUri: http://localhost:9000/api

types:

  Folder:
    type: object
    properties:
      files:
        type: object
        properties:
          /^S-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/:
            type: File
    example:
      files:
        'S-75b4-431b-adb2-eb6b9e546014':
          title: "A sample file"
          pages:
            -
              lines:
                -
                  index: 0
                -
                  index: 1
            -
              lines: []

  File:
    type: object
    properties:
      title: string
      pages: Page[]

  Page:
    type: object
    properties:
      lines:
        type: array
        items:
          type: object
          properties:
            index:
```

The parser returns an error on line 17 (`files` node) with "string is expected". It actually does not say anything about that `index` expects a string on `index: 0` and `index: 1`. Can we improve the error message and position here pls. For me there should be two errors reported, both indicating that the value of `index` is not a string or you expect a string but have an integer / number / whatever.
