### ISSUE TITLE
Type name node is marked for errors in annotations of the type

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#429]
For example,
```
#%RAML 1.0
title: test API

annotationTypes:
  a1:
    properties:
      p1:
        properties:
          p2: number

types:
  MyType:
    type: object
    (a1):
      p1:
        p2: asd
```

![annotationsontypes](https://cloud.githubusercontent.com/assets/6206034/17871034/0d0bbeee-68e4-11e6-80b8-b6bb2430848e.png)

The issue is reproduces for types, their properties and method/response bodies.
