### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#43]
Hi, I'm unclear how to get info about my annotations. I have annotations on my methods. I just want to know how to get the annotation name and value.

raml
```
annotationTypes:
  handler:
    parameters:
      value: string

  /clients:
    get:
      (handler): routes.resources.clients.list
```

ast
```
[ AnnotationRefImpl {
    attr: 
     ASTPropImpl {
       _node: [Object],
       _parent: [Object],
       _implicit: false,
       values: {},
       _def: [Object],
       _prop: [Object],
       fromKey: false } } ]
```
