### ISSUE TITLE
parser 1.0.0 not expanding traits from extended file

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#437]
base.raml:
```
#%RAML 1.0

...

traits:
  secure:
    securedBy: oath2
```

api.raml:
```
#%RAML 1.0 Extension

extends: ./base.raml

/foo:
  is: [ secure ]
  get:
```

loader.js
```
let ast = await raml.loadApi('api.raml');
ast = ast.expand();
```

After expansion `foo` has no securedBy schemas. If I move the trait into api.raml it works. This used to work with older version of the parser, so this is a regression I assume.
