### ISSUE TITLE
array doesn't seem to be recognized

### ISSUE THREAD

**Issue by brettkroeder** [raml-org/raml-js-parser-2#439]
I have a customer raml defined as:

```
#%RAML 1.0 DataType
    properties:
      sourceSystem: string
      customerId?: string
      mdmId?: string
      customerType?: string
      customerName: string
      phoneNumbers?:
        type: array
        items: !include phone.raml
        minItems: 1
```

I have an example defined as

```
#%RAML 1.0 NamedExample
sourceSystem: Salesforce A
customerId: "1"
mdmId: a1
customerType: Residential
customerName: Roeder Consulting
phoneNumbers:
  - phoneType: Main
    phoneNumber: 404-447-6386
    preferred: yes
  - phoneType: Home
    phoneNumber: 678-614-5006
```

When I test a method I get

```
{
  "error": "body: phoneNumbers: cannot be repeated"
}
```

Given `phoneNumbers` is defined as an array I shouldn’t be getting this error.
