### ISSUE TITLE
Seems we don't support piping functions for parameters

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#446]
The following `<<resourcePathName|!singularize|!uppercamelcase>>` is not being resolved by the parser.

Lets assume I have the following input RAML for the parser:

```yaml
#%RAML 1.0
title: Issue Example

resourceTypes:
  collection:
    description: Get a list of <<resourcePathName|!singularize|!uppercamelcase>>

/collections:
  type: collection
```

I am getting the following out:

```json
{
   "resourceTypes":[
      {
         "collection":{
            "description":"Get a list of <<resourcePathName|!singularize|!uppercamelcase>>",
            "name":"collection"
         }
      }
   ],
   "title":"Issue Example",
   "resources":[
      {
         "type":"collection",
         "description":"Get a list of <<resourcePathName|!singularize|!uppercamelcase>>",
         "relativeUri":"/collections",
         "displayName":"/collections",
         "__METADATA__":{
            "primitiveValuesMeta":{
               "displayName":{
                  "calculated":true
               }
            }
         },
         "relativeUriPathSegments":[
            "collections"
         ]
      }
   ]
}
```

What I would expect is that the description contains "Collection". Removing `!uppercamelcase` , the description contains "Get a list of collection".
