### ISSUE TITLE
xml attribute=true does not work

### ISSUE THREAD

**Issue by brettkroeder** [raml-org/raml-js-parser-2#448]
I am trying to generate attributes instead of elements.

My types are defined as:

```
#%RAML 1.0 Library
types:
  AddCollectRefund:
    properties:
      AddCollectRefund: 
        type: string
        xml:
          attribute: true

  Difference:
    properties:
      Difference: 
        type: string
        xml:
          attribute: true

  DifferenceFare:
    properties:
      DifferenceFare: 
        type: string
        xml:
          attribute: true

  DifferenceTax:
    properties:
      DifferenceTax: 
        type: string
        xml:
          attribute: true

  Fee:
    properties:
      Fee: 
        type: string
        xml:
          attribute: true

  ExchangeDetails:
    properties:
      AddCollectRefund?: AddCollectRefund[]
      Difference?: Difference[]
      DifferenceFare?: DifferenceFare[]
      DifferenceTax?: DifferenceTax[]
      Fee?: Fee[]
```

My NamedExample is:

```
#%RAML 1.0 NamedExample
      ExchangeDetails:
        - AddCollectRefund:
            Amount: "100.00"
        - Difference:
            Amount: "100.00"
        - DifferenceFare:
            Amount: "50.00"
        - DifferenceTax:
            Amount: "10.00"
        - Fee:
            Amount: "100.00"
```

The result is:

```
<response>
    <ExchangeDetails>
        <ExchangeDetail>
            <AddCollectRefund>
                <Amount>100.00</Amount>
            </AddCollectRefund>
        </ExchangeDetail>
        <ExchangeDetail>
            <Difference>
                <Amount>100.00</Amount>
            </Difference>
        </ExchangeDetail>
        <ExchangeDetail>
            <DifferenceFare>
                <Amount>50.00</Amount>
            </DifferenceFare>
        </ExchangeDetail>
        <ExchangeDetail>
            <DifferenceTax>
                <Amount>10.00</Amount>
            </DifferenceTax>
        </ExchangeDetail>
        <ExchangeDetail>
            <Fee>
                <Amount>100.00</Amount>
            </Fee>
        </ExchangeDetail>
    </ExchangeDetails>
</response>
```

when it should be:

```
<response>
    <ExchangeDetails>
        <ExchangeDetail>
            <AddCollectRefund Amount=100.00</AddCollectRefund>
        </ExchangeDetail>
        <ExchangeDetail>
            <Difference Amount=100.00</Difference>
        </ExchangeDetail>
        <ExchangeDetail>
            <DifferenceFare Amount=50.00</DifferenceFare>
        </ExchangeDetail>
        <ExchangeDetail>
            <DifferenceTax Amount=10.00</DifferenceTax>
        </ExchangeDetail>
        <ExchangeDetail>
            <Fee Amount=100.00</Fee>
        </ExchangeDetail>
    </ExchangeDetails>
</response>
```

[Ticketing.zip](https://github.com/raml-org/raml-js-parser-2/files/464124/Ticketing.zip)
