### ISSUE TITLE
Library expansion is not working

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#451]
Lets assume we have the following library called `lib.raml`:

```yaml
#%RAML 1.0 Library

traits:
  pagination:
    queryParameters:
      offset:
        type: integer
      limit:
        type: integer
  searchable:
    queryParameters:
      query:

annotationTypes:
  hypermedia-control:
    allowedTargets: [ TypeDeclaration, Method ]
    properties:
      method?:
        description: Which method should be executed on resource?
        default: get
      visible?:
        type: boolean
        description:  Should client should provide link to user?
        default: true
      targetResource:
        type: string
        description: Resource as defined in this API
      follow?:
        type: boolean
        description: Should client invoke the url upon reception?
  info:
    properties:
      author?: string
      title?: string
      description?: string
      termsOfServiceUrl?: string
      contact?: string
      license?: string
      licenseUrl?: string
    allowedTargets: API
types:
  Test: string
  Person:
    type: object
    properties:
      name: string
  Artist:
    type: object
    properties:
      name:
        type: string
        example: "The Beatles"
      is_band:
        type: boolean
        example: true
  Song:
    type: object
    properties:
      description?: string
      title:
        type: string
        example: "Yesterday"
      artist: Artist
  Artists: Artist[]
  Songs: Song[]
```

and a root RAML file called `api.raml`:

```yaml
#%RAML 1.0
title: Issue Example

types:
  Dog:
    properties:
      version:
        example: "1.1"

uses:
  lib: lib.raml

/songs:
  get:
    responses:
      200:
        body:
          application/json:
            type: lib.Songs
/collections:
  get:
    responses:
      200:
        body:
          application/json:
            type: Dog
```

I am not able to see the `Songs` type inside the final output, but strangely enough some trait definition that I have not used at all. Please see the following JSON representation of the output:

```json
{
   "uses":[
      {
         "key":"lib",
         "value":"lib.raml"
      }
   ],
   "types":[
      {
         "Dog":{
            "name":"Dog",
            "displayName":"Dog",
            "type":[
               "object"
            ],
            "required":true,
            "properties":{
               "version":{
                  "name":"version",
                  "displayName":"version",
                  "type":[
                     "string"
                  ],
                  "example":"1.1",
                  "required":true,
                  "__METADATA__":{
                     "primitiveValuesMeta":{
                        "displayName":{
                           "calculated":true
                        },
                        "type":{
                           "insertedAsDefault":true
                        },
                        "required":{
                           "insertedAsDefault":true
                        }
                     }
                  },
                  "structuredExample":{
                     "value":"1.1",
                     "strict":true,
                     "name":null,
                     "structuredValue":"1.1"
                  }
               }
            },
            "__METADATA__":{
               "primitiveValuesMeta":{
                  "displayName":{
                     "calculated":true
                  },
                  "type":{
                     "insertedAsDefault":true
                  },
                  "required":{
                     "insertedAsDefault":true
                  }
               }
            }
         }
      }
   ],
   "traits":[
      {
         "lib.pagination":{
            "queryParameters":{
               "offset":{
                  "name":"offset",
                  "displayName":"offset",
                  "type":[
                     "integer"
                  ],
                  "required":true,
                  "__METADATA__":{
                     "primitiveValuesMeta":{
                        "displayName":{
                           "calculated":true
                        },
                        "required":{
                           "insertedAsDefault":true
                        }
                     }
                  }
               },
               "limit":{
                  "name":"limit",
                  "displayName":"limit",
                  "type":[
                     "integer"
                  ],
                  "required":true,
                  "__METADATA__":{
                     "primitiveValuesMeta":{
                        "displayName":{
                           "calculated":true
                        },
                        "required":{
                           "insertedAsDefault":true
                        }
                     }
                  }
               }
            },
            "name":"lib.pagination",
            "__METADATA__":{
               "calculated":true
            }
         }
      },
      {
         "lib.searchable":{
            "queryParameters":{
               "query":{
                  "name":"query",
                  "displayName":"query",
                  "type":[
                     "string"
                  ],
                  "required":true,
                  "__METADATA__":{
                     "primitiveValuesMeta":{
                        "displayName":{
                           "calculated":true
                        },
                        "type":{
                           "insertedAsDefault":true
                        },
                        "required":{
                           "insertedAsDefault":true
                        }
                     }
                  }
               }
            },
            "name":"lib.searchable",
            "__METADATA__":{
               "calculated":true
            }
         }
      }
   ],
   "title":"Issue Example",
   "resources":[
      {
         "methods":[
            {
               "responses":{
                  "200":{
                     "code":"200",
                     "body":{
                        "application/json":{
                           "name":"application/json",
                           "displayName":"application/json",
                           "type":[
                              "lib.Songs"
                           ],
                           "required":true,
                           "__METADATA__":{
                              "primitiveValuesMeta":{
                                 "displayName":{
                                    "calculated":true
                                 },
                                 "required":{
                                    "insertedAsDefault":true
                                 }
                              }
                           }
                        }
                     }
                  }
               },
               "method":"get"
            }
         ],
         "relativeUri":"/songs",
         "displayName":"/songs",
         "__METADATA__":{
            "primitiveValuesMeta":{
               "displayName":{
                  "calculated":true
               }
            }
         },
         "relativeUriPathSegments":[
            "songs"
         ]
      },
      {
         "methods":[
            {
               "responses":{
                  "200":{
                     "code":"200",
                     "body":{
                        "application/json":{
                           "name":"application/json",
                           "displayName":"application/json",
                           "type":[
                              "Dog"
                           ],
                           "example":{
                              "version":"1.1"
                           },
                           "required":true,
                           "__METADATA__":{
                              "primitiveValuesMeta":{
                                 "displayName":{
                                    "calculated":true
                                 },
                                 "required":{
                                    "insertedAsDefault":true
                                 }
                              }
                           },
                           "structuredExample":{
                              "value":"{\n  \"version\": \"1.1\"\n}",
                              "strict":true,
                              "name":null,
                              "structuredValue":{
                                 "version":"1.1"
                              }
                           }
                        }
                     }
                  }
               },
               "method":"get"
            }
         ],
         "relativeUri":"/collections",
         "displayName":"/collections",
         "__METADATA__":{
            "primitiveValuesMeta":{
               "displayName":{
                  "calculated":true
               }
            }
         },
         "relativeUriPathSegments":[
            "collections"
         ]
      }
   ]
}
```

I am using 1.1.1, and looking at the release notes for 1.1.0 library expansion should be supported.
