### ISSUE TITLE
Parser does not return error when RAML file has empty traits or empty types

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#460]
Having this example at API Designer , I don´t get error feedback when adding empty type or empty trait node

``` yaml
#%RAML 1.0
title: API test
baseUri: https://apitest.com/api
documentation:
 - title: Home
   content: |
     this is a comment

types: {}
traits: [] 
```
