### ISSUE TITLE
Pattern / additional properties are wrongly validated by the parser

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#462]
Lets assume you have the following example (taken from the spec):

```yaml
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      //: # force all additional properties to be a string
        type: string
```

The parser currently throws a warning that there are conflicting properties but  `//` should only be tested against the “additional” properties not the ones the has been defined already.

The spec and the examples in there are very clear but here I am getting a different behaviour from the parser. From the spec

> This pattern property restricts any additional properties ...
