### ISSUE TITLE
"value" in array example does not work

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#469]
Lets assume we have the following library definition:

```yaml
types:
  Product:
    properties:
      product_id:
      quantity: integer
    examples:
      single-product:
        value:
          product_id: "PRODUCT-1"
          quantity: 4
  Order:
    properties:
      order_id:
      creation_date:
      items: Product[]
  Orders:
    properties:
      orders: Order[]
    examples:
      single-order:
        orders:
          strict: false
          value:
            -
              order_id: "ORDER-437563756"
              creation_date: "2016-03-30"
              items:
                -
                  product_id: "PRODUCT-1"
                  quantity: 5
                -
                  product_id: "PRODUCT-2"
                  quantity: 2
      multiple-orders:
        orders:
            -
              order_id: "ORDER-437563756"
              creation_date: "2016-03-30"
              items:
                -
                  product_id: "PRODUCT-1"
                  quantity: 5
                -
                  product_id: "PRODUCT-2"
                  quantity: 2
            -
              order_id: "ORDER-437542111"
              creation_date: "2016-03-30"
              items:
                -
                  product_id: "PRODUCT-7"
                  quantity: 6
```

As you can see I have multiple `examples` definition. the first on `Product` type which shows you that `value` is working with a single item example. A second on `Orders` called `single-order` which also defines a `value` node with an array this time, and a third called `multiple-orders` that defines no `value` node for the array example.

The `single-order` fails and the parser tells me that an array is expected. Deleting `value` removes the error message. Really odd since I should be able to define the example either directly on the example key or using the `value` node.

**Comment by KonstantinSviridov** [comment]
Hi, Christian.
It should be
```
      single-order:
          strict: false
          value:
            orders:
```
, not
