### ISSUE TITLE
getting media types of post bodies

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#48]
```
/login:
  description: Redirect to accounts api login
  get:
    (handler):
      path: 'login.page'
  post:
    (handler):
      path: 'login.post'
    body:
      application/json:
        type: object
        properties:
          username: string
          password: string
      application/x-www-form-urlencoded:
        type: object
        properties:
          username: string
          password: string
```

I can't find any way to get the post body media types. From a method node I can get bodies but that is just the object definitions underneath the media types.
