### ISSUE TITLE
Validation example apparently has no sense

### ISSUE THREAD

**Issue by fescobar** [raml-org/raml-js-parser-2#482]
In the line 495 the designer shows a message about the schema. We tried to update the example according to the schema but always it appears the same validation.

![validating schemas in raml 0 8](https://cloud.githubusercontent.com/assets/1236418/18840171/101194ea-83e4-11e6-8848-78409b6cf21f.png)

[API_Platform-v2.0.3.zip](https://github.com/raml-org/raml-js-parser-2/files/493433/API_Platform-v2.0.3.zip)

**Comment by ddenisenko** [comment]
`schema` node should be inside `application/json`:
```
            /addRootRaml:
              post:
                description: Adds the root RAML for this API version.
                body:
                  application/json:
                    schema: addRootRaml
                    example: !include examples/organizations_organizationId_apis_apiId_versions_versionId_addRootRaml_post_request.json
```
