### ISSUE TITLE
Survive recursive includes outside of types

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#487]
Parser stack should not explode for the following RAML:

```
#%RAML 1.0 Library
uses:
  - File2: !include file2.raml

types:
  Base:
    type: object
    properties:
      name: string
  Full:
    type: Base
    properties:
      file2s: File2.Base[]

```

```
#%RAML 1.0 Library
uses:
  - File1: !include file1.raml

types:
  Base:
    type: object
    properties:
      name: string
  Full:
    type: Base
    properties:
      file1: File1.Base

```
