### ISSUE TITLE
Parser should not explode on illegal use of includes in uses

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#488]
Like the following one:

```
#%RAML 1.0 Library
uses:
  - File2: !include file2.raml

types:
  Base:
    type: object
    properties:
      name: string
  Full:
    type: Base
    properties:
      file2s: File2.Base[]
```
