### ISSUE TITLE
Media type error trace is broken + request to allow custom media types

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#489]
I noticed when using some custom media types I get an error like this:
`endpoints/channels.raml@undefined:undefined invalid media type`

The media type I tried to use was `application/x-mpegurl` which is not in RFC6838 but is widely used (see google).

Can we please have an option to allow for custom media types?

**Comment by ddenisenko** [comment]
Following sample does not produce any errors for me:

```
#%RAML 1.0
title: test api
version: v1

/test:
  post:
    description: Get customer
    body:
      application/x-mpegurl:

```

Could you please provide a complete RAML sample?
