### ISSUE TITLE
type.validateInstance returns no errors if additional properties are present

### ISSUE THREAD

**Issue by tebs1200** [raml-org/raml-js-parser-2#516]
I've noticed that the `validateInstance` function isn't returning any errors if you have an object type and pass in an object that has extra parameters not specified in the schema.

```
# example.raml

#RAML 1.0
title: Test API
version: 0.0.1
mediaType: application/json

types:
  Rating:
    type: object
    properties:
      value:
        type: integer
        minimum: 1
        maximum: 10
      iconPrefix: string
    example:
      value:
        value: 3
        iconPrefix: star
```

Notice that I've included the `extra` parameter in the example `Rating`, but no error is generated by the validation.

```
// example.js
var ramlParser = require('raml-1-parser'),
    changeCase = require('change-case');

apiSpec = ramlParser.loadApiSync('example.raml', {rejectOnErrors: true});

var ramlTypes = {};
apiSpec.types().forEach(function(type) {
    ramlTypes[changeCase.camelCase(type.name())] = type;
});

let ratingWithExtraProperty = {
    value: 7,
    iconPrefix: 'smile',
    extra: 'test'
};

let validationErrors = ramlTypes.rating.validateInstance(ratingWithExtraProperty);

validationErrors.forEach(function(error) {
    console.log(error);
});

console.log('There were ' + validationErrors.length + ' errors. There should be 1');
```

**Comment by sichvoge** [comment]
Additional properties is by default `true`. Hence, you shouldn't get any errors.

**Comment by tebs1200** [comment]
Is there a way to specify that objects with additional unspecified properties are invalid?

**Comment by sichvoge** [comment]
Yes, you only have to set `additionalProperties` to `false`.

```
Person:
  additionalProperties: false
  properties:
    name: string
```
