### ISSUE TITLE
Only 2 levels of error traces are serialized to JSON

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#517]
Sample:

test50.raml:
```
#%RAML 1.0
title: Test
baseUri: http://{a}.myapi.org

uses:
  test50Library: test50library.raml

types:
  TestType:
    properties:
      firstPrtop: string
      thirdProp: test50Library.LibType1

```

test50library.raml:
```
#%RAML 1.0 Library
uses:
  test50Library2: test50library2.raml

types:
  LibType1:
    properties:
      testProp123: test50Library2.LibType2

```

test50library2.raml:
```
#%RAML 1.0 Library

types:
  LibType2:
    properties:
      testProp1234: string
blah:

```

Parse `test50.raml`. 
There is an error in `test50library2.raml` file, but the result error only contains 1 level of trace, instead of expected 2 levels.
