### ISSUE TITLE
Incorrect error trace when including API as a type

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#518]
Lets assume I have the following example:

types.raml
```yaml
#%RAML 1.0
title: types def

types:
  song:
    type: object
    properties:
      name: string
    example:
      name: ss
```

api.raml
```yaml
#%RAML 1.0
title: testing include raml

types: !include types.raml
```

The parser does not throw any error when including the `types.raml` file. Why is that? Should `include` take the nodes and attach them to the node where its being used? Even changing `types` to `schemas` did not bring up any problems.
