### ISSUE TITLE
Multiple examples are not serialized to JSON when included from external JSON files

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#519]
RAML:

```
#%RAML 1.0
title: test
types:
  TestType:
    properties:
      message: string
    examples:
      One: !include examples/Blah.json
      Two: !include examples/Blah.json
/test:
  post:
    body:
      application/json:
        type: TestType

```

Blah.json contains JSON.

Result: toJSON of the top-level node results in no `One` and `Two` examples mentioned.
