### ISSUE TITLE
`discriminatorValue` must be validated for being null

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#525]
Discriminator property type must be scalar and, thus, can not be nilable. So an error must be produced for the following RAML:
```
ParentType:
  properties:
    key:

MyType:
  type: ParentType
  discriminatorValue:
```
