### ISSUE TITLE
queryString & queryParameter are mutual exclusive

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#539]
Having the following example

```yaml
#%RAML 1.0
title: Traits

traits:
  box:
    queryParameters:
      param: string
  container:
    is: [box]
    body:
      application/json:
    headers:
      auth: string
    queryString:
      properties:
```

Shouldn't I get an error since `queryParameter` and `queryString` are mutual exclusive? the spec clearly states:

> The queryString and queryParameters nodes are mutually exclusive: processors MUST NOT allow both to be specified, explicitly or implicitly, on the same method of the same resource.
