### ISSUE TITLE
Incorrect error object returned while working with an invalid Trait fragment

### ISSUE THREAD

**Issue by agustinlg** [raml-org/raml-js-parser-2#543]
Having this in file pagination.raml:

```yaml
#%RAML 1.0 Trait
queryParameters:
  <<queryParamName>>:
    description: This is a <<queryParamName>> value parameter.
    offset:
      description: Skip over a number of elements by specifying an offset value for the query
      type: integer
```

And this in api.raml:

```yaml
#%RAML 1.0
title: API Animals & People!

traits: 
  pagination: !include pagination.raml  
      
/some:
  get:
    is: [pagination]
```

Returned errors are:

```json
[
  {
    "code": 3,
    "message": "Value is not provided for parameter: 'queryParamName'",
    "path": "api.raml",
    "range": {
      "start": {
        "line": 0,
        "column": -1,
        "position": -1
      },
      "end": {
        "line": 0,
        "column": -1,
        "position": -1
      }
    }
  },
  {
    "code": 11,
    "message": "Specifying unknown facet: 'offset'",
    "path": "pagination.raml",
    "range": {
      "start": {
        "line": 4,
        "column": 4,
        "position": 123
      },
      "end": {
        "line": 4,
        "column": 10,
        "position": 129
      }
    },
    "trace": [
      {
        "code": 11,
        "message": "Specifying unknown facet: 'offset' pagination.raml",
        "path": "pagination.raml",
        "range": {
          "start": {
            "line": 8,
            "column": 10,
            "position": 123
          },
          "end": {
            "line": 8,
            "column": 16,
            "position": 129
          }
        }
      }
    ]
  }
]
```

This is what's being shown at the designer:

The error object should have an error pointing to the include of the trait in line 5 in api.raml, and then the trace error object:
<img width="475" alt="screen shot 2016-11-14 at 7 30 06 pm" src="https://cloud.githubusercontent.com/assets/1583786/20285463/d28db016-aaa0-11e6-8c31-8c284a647c60.png">

Also, there is ONLY an error in api.raml, pagination.raml doesn't throw any error:
<img width="527" alt="screen shot 2016-11-14 at 7 30 21 pm" src="https://cloud.githubusercontent.com/assets/1583786/20285462/d28dce98-aaa0-11e6-938a-7c6d0d071223.png">
