### ISSUE TITLE
value in protocols is case-insensitive

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#547]
The RAML 1.0 spec clearly defines that

> The protocols node MUST be a non-empty array of strings, of values HTTP and/or HTTPS, and is case-insensitive.

With the example below, the parser throws me an error that `https` is not allowed.

```yaml
#%RAML 1.0
title: Simple API
version: 1.1.0
protocols: [ https ]
```

![image](https://cloud.githubusercontent.com/assets/498114/20386116/0e2378d2-acb2-11e6-950b-65f3fd5688c8.png)
