### ISSUE TITLE
parser should throw error when unknown scope is defined

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#548]
Let's look at the following example for RAML 1.0:

```yaml
securitySchemes:
  OauthSecurity:
    description: New Oauth security system. Do not use MediaSecurity or LegacySecurity.
    type: OAuth 2.0
    settings:
      authorizationGrants: [ authorization_code ]
      authorizationUri: 'https://oauth.simple.api/authorization'
      accessTokenUri: 'https://oauth.simple.api/token'
      scopes: [ admin, user ]

securedBy: [ OauthSecurity: { scopes: [ hello ] } ]
```

The spec allows me to define a `scopes` parameter when you apply a specific security scheme. The parser does not complain, but also does not complain when I define a scope that is not defined inside the security scheme. Shouldn't the parser tell me that there is something wrong?
