### ISSUE TITLE
Applying traits parameter does not work as expected

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#568]
Using the [this example](https://github.com/advanced-rest-client/raml-example-api) it seems that the parameter value for `resourceType` at line 170 inside `api.raml` does not get propagated. 

The final result is that the `items` type is `string[]` for some reason.

![image](https://cloud.githubusercontent.com/assets/498114/20895240/818be202-bb10-11e6-9d94-67fa6ee558ba.png)

The items definition inside `pagination.raml` is:

```yaml
items:
  type: array
  required: true
  description: Contains a list of objects for this method.
  items: [ <<resourceType>> ]
```

Funny thing is, removing both `[` and `]` from this definition, I get another error saying the following: 

![image](https://cloud.githubusercontent.com/assets/498114/20895360/0e59df2c-bb11-11e6-975b-eb55f80474c5.png)
