### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#573]
Consider the following RAML spec:
```yaml
#%RAML 1.0
title: test API

traits:
  tr:
    body:
      application/json:
        type: string

/folders:
  post:
    is: [ tr ]
    body:
      application/json: !include
```

after one finishes typing `!include` on the last line, the exception is thrown:
```
TypeError: Cannot read property 'absolutePath' of null
    at ReferencePatcher.appendUnitIfNeeded (raml-js-parser-2\dist\raml1\ast.core\referencePatcher.js:503:71)
    at ReferencePatcher.patchReferences (raml-js-parser-2\dist\raml1\ast.core\referencePatcher.js:75:33)
    at ReferencePatcher.patchReferences (raml-js-parser-2\dist\raml1\ast.core\referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (raml-js-parser-2\dist\raml1\ast.core\referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (raml-js-parser-2\dist\raml1\ast.core\referencePatcher.js:88:18)
    at ReferencePatcher.process (raml-js-parser-2\dist\raml1\ast.core\referencePatcher.js:35:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (raml-js-parser-2\dist\raml1\ast.core\expander.js:115:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (raml-js-parser-2\dist\raml1\ast.core\expander.js:93:27)
    at Object.expandTraitsAndResourceTypes (raml-js-parser-2\dist\raml1\ast.core\expander.js:29:10)
    at expandTraitsAndResourceTypes (raml-js-parser-2\dist\raml1\wrapped-ast\wrapperHelper.js:86:21)
```
