### ISSUE TITLE
Share RAML libraries - workqround 

### ISSUE THREAD

**Issue by pokraev** [raml-org/raml-js-parser-2#574]
I'm trying to work around the limitation of importing a library from protected location. To do that, I put my library on Dropbox and create a share link that looks like that:

`https://www.dropbox.com/s/jo0xufqrngf4t5b/types.raml?raw=1`

that contains 
```yaml 
#%RAML 1.0 Library
types:
  Customer:
    properties:
      id: string
      name: string  
```

Then, I try to import the library:
```yaml
#%RAML 1.0 Library
uses:
  lib: https://www.dropbox.com/s/jo0xufqrngf4t5b/types.raml?raw=1

types:
  VIPCustomer:
    type: lib.Customer
```
but I get an error: `inheriting from unknown type`

Could you please take a look?
