### ISSUE TITLE
Type inheritance does not work properly when additionalProperties is set to true

### ISSUE THREAD

**Issue by asargento** [raml-org/raml-js-parser-2#588]
When parsing the following raml file, I found that the sub type is not expanded properly.
The raml file is
```
#%RAML 1.0
title: Inheritance error
version: v1.0
description: Inheritance does work properly when the subtype has a properties of type array
baseUri: https://test.com
protocols: [HTTP, HTTPS]
mediaType: application/json

types:
  baseType:
    type: object
    properties:
      name:
        type: string
        pattern: "^\\w+$"
    additionalProperties: false

  subType:
    type: baseType
    additionalProperties: false
    properties:
      prop1:
        type: string
        pattern: ^\S+$
        required: false
      prop2:
        type: boolean
        required: false

/api:
  displayName: Api
  /{id}:
    displayName: Class
    post:
      body:
        application/json:
          type: subType
```

The result of parsing this file if **subType additionalProperties** is **true** is different if it has value **false**. The subType is not expanded.
After parsing, on **post** method result is 
```
"body": [{
  "name": "subType",
  "displayName": "subType",
  "type": "baseType",
  "required": true,
  "properties": [{
     "name": "prop1",
     "displayName": "prop1",
     "type": "string",
     "required": false,
     "pattern": "^\\S+$",
     "key": "prop1"
   }, {
     "name": "prop2",
     "displayName": "prop2",
     "type": "boolean",
     "required": false,
     "key": "prop2"
   }],
   "additionalProperties": true,
   "key": "application/json"
}]
```
And it should be equal when setting additionalProperties to false.

```
"body": [{
   "name": "subType",
   "displayName": "subType",
   "type": "object",
   "required": true,
   "additionalProperties": false,
   "properties": [{
     "displayName": "name",
     "type": "string",
     "required": true,
     "pattern": "^\\w+$",
     "key": "name"
   }, {
     "type": "string",
     "displayName": "prop1",
     "name": "prop1",
     "required": false,
     "pattern": "^\\S+$",
     "key": "prop1"
   }, {
     "type": "boolean",
     "displayName": "prop2",
     "name": "prop2",
     "required": false,
     "key": "prop2"
   }],
   "key": "application/json"
}]
```

In attachment, I add the raml and the two result files.
[files.zip](https://github.com/raml-org/raml-js-parser-2/files/678784/files.zip)

**Comment by asargento** [comment]
I found that if a subType property is of type array, this problem also occurs.
The raml example is, where I defined a new property **prop3**
```
#%RAML 1.0
title: Inheritance error
version: v1.0
description: Inheritance does work properly when the subtype has a properties of type array
baseUri: https://test.com
protocols: [HTTP, HTTPS]
mediaType: application/json

types:
  baseType:
    type: object
    properties:
      name:
        type: string
        pattern: "^\\w+$"
    additionalProperties: false

  subType:
    type: baseType
    additionalProperties: false
    properties:
      prop1:
        type: string
        pattern: ^\S+$
        required: false
      prop2:
        type: boolean
        required: false
      prop3:
        type: array
        items:
          type: string

/api:
  displayName: Api
  /{id}:
    displayName: Class
    post:
      body:
        application/json:
          type: subType
```
