### ISSUE TITLE
JSON output misses required property inside a queryString

### ISSUE THREAD

**Issue by agustinlg** [raml-org/raml-js-parser-2#590]
After updating to parser v1.1.11, the json output misses the required property inside a queryString

Having a queryString in an endpoint:
```
get:
  ...
  queryString:
      type: environmentType
      description: my description2
      required: true
```

Output from v1.1.10:
```
{ 
  name: 'queryString',
  type: [ 'environmentType' ],
  required: true,
  description: 'my description2' 
}
```

Output from v1.1.11 misses required property:
```
{ 
  name: 'queryString',
  typePropertyKind: 'TYPE_EXPRESSION',
  type: [ 'environmentType' ],
  description: 'my description2' 
}
```
