### ISSUE TITLE
Question mark to identify optional attributes is lost after parsing

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#593]
When parsing the following RAML file : 
```
#%RAML 1.0
title: type example
version: 1

types:
 ResourceLink:
   description: a description
   facets:
     a: string
     b: number
   properties:
     href: string
     rel:
       enum: [self, next, prev]
     method?:
       default: get
 ImageLink:
   properties:
     href: string
     rel:
       enum: [SmallImage, MediumImage, LargeImage]
```

We get the following json as result of the parsing process. As you can see, the reference of method attribute as optional (marked with the ? mark) is lost.

```
{
    "types": [
        {
            "ResourceLink": {
                "name": "ResourceLink",
                "facets": {
                    "a": {
                        "name": "a",
                        "typePropertyKind": "TYPE_EXPRESSION",
                        "type": [
                            "string"
                        ]
                    },
                    "b": {
                        "name": "b",
                        "typePropertyKind": "TYPE_EXPRESSION",
                        "type": [
                            "number"
                        ]
                    }
                },
                "typePropertyKind": "INPLACE",
                "description": "a description",
                "properties": {
                    "href": {
                        "name": "href",
                        "typePropertyKind": "TYPE_EXPRESSION",
                        "type": [
                            "string"
                        ]
                    },
                    "rel": {
                        "name": "rel",
                        "typePropertyKind": "INPLACE",
                        "enum": [
                            "self",
                            "next",
                            "prev"
                        ]
                    },
                    "method": {
                        "name": "method",
                        "typePropertyKind": "INPLACE",
                        "default": "get"
                    }
                }
            }
        },
        {
            "ImageLink": {
                "name": "ImageLink",
                "typePropertyKind": "INPLACE",
                "properties": {
                    "href": {
                        "name": "href",
                        "typePropertyKind": "TYPE_EXPRESSION",
                        "type": [
                            "string"
                        ]
                    },
                    "rel": {
                        "name": "rel",
                        "typePropertyKind": "INPLACE",
                        "enum": [
                            "SmallImage",
                            "MediumImage",
                            "LargeImage"
                        ]
                    }
                }
            }
        }
    ],
    "title": "type example",
    "version": "1"
}
```
