### ISSUE TITLE
The value of 'additionalProperties' should only be boolean 

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#594]
The parser does not complain about the following example:

```yaml
#%RAML 1.0
title: TestRAML

types:
  Employee:
    type: object
    additionalProperties:
      type: string
```

According to the spec, the value of `additionalProperties` must be a boolean.

![image](https://cloud.githubusercontent.com/assets/498114/21674076/12e416d6-d324-11e6-8bda-677179231edc.png)

Another strange behaviour happens when parsing that example. The result is the following:

```yaml
{
  "types": [
    {
      "Employee": {
        "name": "Employee",
        "displayName": "Employee",
        "typePropertyKind": "TYPE_EXPRESSION",
        "type": [
          "object"
        ],
        "additionalProperties": false,
        "__METADATA__": {
          "primitiveValuesMeta": {
            "displayName": {
              "calculated": true
            }
          }
        }
      }
    }
  ],
  "title": "TestRAML"
}
```

In here, `additionalProperties` is actually `false`.
