### ISSUE TITLE
Counterpart of `dereferenceSchemas` in raml-js-parser-2 ?

### ISSUE THREAD

**Issue by tfayruzov** [raml-org/raml-js-parser-2#598]
I want to expand json schema definitions with refs similarly to what have been done in 0.8 parser with `dereferenceSchemas` flag. Is there a counterpart in 1.0 parser?

I tried to look at the [options](https://github.com/raml-org/raml-js-parser-2/blob/develop/src/raml1/wrapped-ast/parserCoreApi.ts#L31), but it does not seem to have what I need.

**Comment by ddenisenko** [comment]
There is currently no way to join all JSON schemas into a single big file.

Why do you need it? Maybe there is some other way to achieve the goal?

**Comment by tfayruzov** [comment]
We are building new API definitions with RAML, but those APIs use well-established JSON Schema models that are used throughout all of our systems (mostly in async event communications, not in RPC-style). API consumers are not very familiar with those models and while I agree that JSON Schema is not a very good format to document the model, it is the best what we have now. For this case, navigating nested schemas is awkward (as it is not supported by generated documentation).

Essentially, JSON schemas are opaque blobs for RAML and that limits the integrations that we would like to do.

Ideally, I would like to have a datatype that is defined as JSON Schema (possible today) and can also be referenced by JSON Schema id. In the other datatype or method body definitions that use JSON Schema, parser would extract nested $refs and backreference them to corresponding data types. For example:

```
types:
  User:
    type: !include user.schema # id: "example.com/schema/user"
    description: This is a user
  Account:
    type: !include account.schema # id: "example.com/schema/user"
    description: This is an account
/transaction:
  post:
    body:
      type: !include transaction.schema # this schema has $refs to user and account by id
```

Now, in generated API documentation I would be able to navigate to User and Account from Transaction. This functionality is implemented for RAML 1.0 data types, but we can't move all our data model definitions to RAML for multiple reasons. I believe that such integration will be appealing for many people who use JSON Schema as there are no good tools for generating documentation from schemas on the market, and for RAML tooling its just an incremental step that (in my opinion) brings an enormous value.
