### ISSUE TITLE
Possible runtimeType property bug with 1.1.12

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#602]
```
types:
  Foo:
    type: object
    properties:
      foo: string
      bar:
        type: number
        required: false
```

When iteration Foos properties:

```
  type.allProperties().forEach(property => {
    assert(property.isRequired());
  })
```

foo: StringType, isRequired = true
bar: null, isRequired = false < inherits from NumberType, isRequired = false

should bar not be NumberType, isRequired = true?
