### ISSUE TITLE
Unknown facet 'properties' when parsing an array with inheritance 

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#605]
Example:

```yaml
#%RAML 1.0
title: test api

types:
  Hello:
  TestArray:
    type: array
    items:
      type: Hello
      properties:
        test: string
```

I get the following error: 

![image](https://cloud.githubusercontent.com/assets/498114/21852170/f31d02aa-d809-11e6-84e7-e182efaddb45.png)

Change the `type` on items to `object`, the error magically disappears. Anyways, looking at the spec, the example should be perfectly valid.

parser version: 1.1.12
