### ISSUE TITLE
IProperty getKeyRegex returns undefined

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#612]
```
types:
  Foo:
    type: object
    properties:
      foo: string
      /^bar\\d+$/: string
```

With a ref to the IProperty /^bar../.

```
prop.nameId() === '^bar\\d+$' 
prop.getKeyRegexp() === undefined
```

With the '/' removed I have no way to tell this key should be a regex. Should getKeyRegexp return me a value? When I was using the json output I would just regex over the keys and look for `/^\/.*\/$/`.
