### ISSUE TITLE
Invalid usage of custom facets

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#613]
Please, look at the following example, where invalid definition and use of custom facets is being accepted without errors

```yaml
traits:
 pageSize:
   queryParameters:
     pageSize:
       facets:
         exclusiveMinimum: boolean
         exclusiveMaximum: boolean
       type: integer
       description: Number of persons returned
       format: int32
       maximum: 100
       default: 20
       exclusiveMinimum: true
       exclusiveMaximum: false
```

I understand this example should throw an error, as custom facets can be use when defined on a super / base type, through inheritance.
