### ISSUE TITLE
Parser is not validating draft-04 schema

### ISSUE THREAD

**Issue by ashosborne1** [raml-org/raml-js-parser-2#623]
Assume following RAML 0.8 document. 

```yaml
- example-schema: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Test schema showing the issue", 
      "properties": {
        "test1": {
            "type": "string",
            "description": "This property is marked as being required",
            "required": true
        }
      }
    }
```

Validates fine- but is not correct against draft-04. Required facet is not allowed on a specific property anymore
