### ISSUE TITLE
Errors and warnings output when parsing file including <<resourcePathName>>

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#639]
Using the following RAML file:
```
#%RAML 1.0
title: Example API
version: v1
resourceTypes:
  collection:
    usage: 
        This resourceType should be used for any 
        collection of items
    description: 
        The collection of <<resourcePathName>>
    get:
      description: Get all <<resourcePathName>>, optionally filtered
    post:
      description: Create a new <<resourcePathName | !singularize>>


traits:
  secured:
    usage: 
       Apply this to any method that needs to be 
       secured
    description: Some requests require authentication.
    headers:
      access_token:
        description: Access Token
        example: 5757gh76
        required: true
        type: string

/users:
  type: collection
  is: [ secured ]
  get:
  post:
```

```
Parser outputs there messages:
[xmldom error]	element parse error: Error: invalid tagName:<resourcePathName 
@#[line:1,col:19]
[xmldom warning]	unclosed xml attribute 
@#[line:1,col:20]
[xmldom error]	element parse error: Error: invalid tagName:<resourcePathName 
@#[line:1,col:9]
[xmldom warning]	unclosed xml attribute 
@#[line:1,col:10]
[xmldom error]	element parse error: Error: invalid tagName:<resourcePathName 
@#[line:1,col:14]
[xmldom warning]	attribute "|" missed value!! "|" instead2!! 
@#[line:1,col:15]
[xmldom error]	element parse error: Error: invalid attribute:| 
@#[line:1,col:15]
```
