### ISSUE TITLE
Uncaught exception on body inheriting array type

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#641]
For
``` yaml
#%RAML 1.0
title: TestApi
types:
    ArrayOfInt:
        type: array
        items:
            type: integer

/persons:
  post:
    body:
      application/json:
        schema: ArrayOfInt
```
the parser throws an exception:
```
c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:1028
        if (tValue.length == 1 && util.stringEndsWith(tValue[0], "[]")) {
                  ^

TypeError: Cannot read property 'length' of undefined
    at ArrayExpressionTransformer.transform (c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:1028:19)
    at c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:166:29
    at Array.forEach (native)
    at TCKDumper.dumpInternal (c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:164:35)
    at c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:406:40
    at Array.forEach (native)
    at TCKDumper.dumpProperties (c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:273:28)
    at TCKDumper.dumpInternal (c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:119:28)
    at c:\GIT-repos\raml-org\raml-js-parser-2\dist\util\TCKDumper.js:406:40
    at Array.forEach (native)
```
