### ISSUE TITLE
Parsing of GlobalSchemas in RAML 0.8 raises unexpected errors

### ISSUE THREAD

**Issue by JonathanMontane** [raml-org/raml-js-parser-2#642]
The RAML 0.8 spec specifies that:
> The value of the schemas property is an array of maps; in each map, the keys are the schema name, and the values are schema definitions.

**Expected**
The following schemas object does not raise errors from the parser
```yaml
schemas:
  - SongId: '{ type: "integer" }'
    SongDuration: '{ type: "number" }'
  - SongType: |
      {
        type: "string",
        enum: [ "jazz", "pop" ]
      }
  - SongName: |
      {
        type: "string"
      }
```
```js
api.errors() === []
```

**Actual**
```js
api.errors() === [
  { 
    code: 'UNKNOWN_NODE', 
    message: 'Unknown node: \'\'',
    ...
  },
  {
    code: 'INVALID_VALUE_SCHEMA',
    message: 'Invalid value schema: \'{\n  type: "string",\n  enum: [ "jazz", "pop" ]\n}\n\'',
    ...
  },
  {
    code: 'INVALID_VALUE_SCHEMA',
    message: 'Invalid value schema: \'{\n  type: "string"\n}\n\'',
    ...
  }
]
```

The `UNKNOWN_NODE` error is associated with the `{ SongId, SongDuration }` map. It seems that the parser fails to parse Maps of Schemas correctly

The `INVALID_VALUE_SCHEMA` is confusing to me. What is incorrect in these two schemas ? They seem pretty similar to the ones from [http://raml.org/developers/raml-200-tutorial#extract-schemas](http://raml.org/developers/raml-200-tutorial#extract-schemas). I tried adding the `$schema` field to see if that changed anything, but it did not.

Could anyone provide me with more information as to whether I'm bad at writing global schemas in the 0.8 syntax, or if there is actually a bug with the parser and the 0.8 syntax? Thanks
