### ISSUE TITLE
items facet in array's should only be a reference or inline type

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#644]
The specification states that the value of items is either a reference to an existing type or an inline type declaration. So the following shouldn't be valid, but the parser does not complain:

```yaml
types:
  Foo:
  Bar:
  FooBarArray:
    type: array
    items: [ Foo, Bar ]
```

I added a test to our TCK [here](https://github.com/raml-org/raml-tck/blob/master/tests/raml-1.0/Types/ArrayTypes/itemsInvalidTypeTest/input.raml).

We still discuss what happens in cases like `items: Foo | Bar`.
