### ISSUE TITLE
enum on object types should be valid

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#650]
Example:

```yaml
#%RAML 1.0
title: myApi

types: 
  Foo: 
    type: object
    properties:
      id: string
      name: string
      age: integer
    enum:
      - id: 12345fr
        name: Foo
        age: 23
      - id: 12345gr
        name: Bar
        age: 12
```

The parser complains that enum is only allowed on scalar values which is, according to the spec, not true.
