### ISSUE TITLE
Property type not being imported correctly

### ISSUE THREAD

**Issue by lbauret** [raml-org/raml-js-parser-2#651]
In the following RAML 1.0 api, the type `Search-result` has a `likes` property whose type is defined in vk-likes.raml. When parsing this api both `Vk-likes` and `Search-result` are generated as data types, but the`likes` property type in `Search-result` is defined inline as in vk-likes.raml.
Instead, it should be a reference to the generated `Vk-likes` data type. 

api.raml
```
#%RAML 1.0
title: Example
version: v1
types:
  Vk-likes: !include models/vk-likes.raml
  Search-result: !include models/search-result.raml
```

search-result.raml
```
#%RAML 1.0 DataType
type: object
properties:
  likes:
    description: include example
    type: !include vk-likes.raml
```

vk-likes.raml
```
#%RAML 1.0 DataType
type: object
properties:
  lastUpdate:
    description: 'last update'
    required: false
    type: datetime-only
```

This is the parsed output:

```
{
   "types": [
      {
         "Vk-likes": {
            "name": "Vk-likes",
            "typePropertyKind": "TYPE_EXPRESSION",
            "type": [
               "object"
            ],
            "properties": {
               "lastUpdate": {
                  "name": "lastUpdate",
                  "typePropertyKind": "TYPE_EXPRESSION",
                  "type": [
                     "datetime-only"
                  ],
                  "required": false,
                  "description": "last update"
               }
            }
         }
      },
      {
         "Search-result": {
            "name": "Search-result",
            "typePropertyKind": "TYPE_EXPRESSION",
            "type": [
               "object"
            ],
            "properties": {
               "likes": {
                  "name": "likes",
                  "typePropertyKind": "INPLACE",
                  "description": "include example",
                  "type": {
                     "name": "type",
                     "typePropertyKind": "TYPE_EXPRESSION",
                     "type": [
                        "object"
                     ],
                     "properties": {
                        "lastUpdate": {
                           "name": "lastUpdate",
                           "typePropertyKind": "TYPE_EXPRESSION",
                           "type": [
                              "datetime-only"
                           ],
                           "required": false,
                           "description": "last update"
                        }
                     }
                  }
               }
            }
         }
      }
   ],
   "title": "Example",
   "version": "v1"
}
```
