### ISSUE TITLE
ArrayTypeDeclaration.items() does not return a TypeDeclaration object

### ISSUE THREAD

**Issue by akallem** [raml-org/raml-js-parser-2#653]
ArrayTypeDeclaration.items() does not return a TypeDeclaration object.

For example, the sample in `GettingStarted.md` in the "Array Types" section (pasted below) fails because `type.items()` is an empty array.
```
api.types().forEach(function (type) {

    if(type.kind() == 'ArrayTypeDeclaration') {
        console.log(type.name() + " : " + type.kind());
        console.log("\t", "items : ", type.items().kind());
    }

});
```

In the example below, `items()` returns as `['string']`:
```
#%RAML 1.0
title: Test
version: 1

types:
  TestArray:
    type: array
    items: string
```

And in this example below, `items()` is `null`.
```
#%RAML 1.0
title: Test
version: 1

types:
  TestArray:
    type: array
    items:
        type: string
```
