### ISSUE TITLE
Cannot include example as parameter

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#657]
Let's assume the following RAML file:

```yaml
#%RAML 1.0
title: Flights-01
version: 1.0

resourceTypes:
  collection:
    get:
      responses: 
        200:
          body: 
            application/json:
              example: <<exampleCollection>>
      
/flights:
  type:
    collection: 
      exampleCollection: !include example.raml
```

**example.raml** 

```yaml
- ID: 1
  code: ER38sd
  price: 400
  departureDate: 2016/03/20
  origin: MUA
  destination: SFO
  emptySeats: 0
  plane: 
    type: Boeing 737
    totalSeats: 150
- ID: 2
  code: ER45if
  price: 345.99
  departureDate: 2016/02/11
  origin: MUA
  destination: LAX
  emptySeats: 52
  plane: 
    type: Boeing 777
    totalSeats: 300
```

What I get from the parser is this:

```
@#[line:1,col:1]
[xmldom warning]	unclosed xml attribute 
@#[line:1,col:2]
error
{"parserErrors":[{"code":"OBJECT_EXPECTED","message":"object is expected","path":"test6.raml","range":{"start":{"line":11,"column":14,"position":171},"end":{"line":11,"column":21,"position":178}},"isWarning":false,"trace":[{"code":"OBJECT_EXPECTED","message":"object is expected","path":"test6.raml","range":{"start":{"line":13,"column":0,"position":203},"end":{"line":13,"column":8,"position":211}},"isWarning":false}]}]}
```

1. That's definitely  a bug inside the parser.
2. What's all the `xmldom` errors that I have seen more recently coming from the parser?
