### ISSUE TITLE
Trait expansion failing in extension

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#658]
Hi. My extension is failing to expand traits. But it seems fairly dodgy >

trait.raml
```yaml
#%RAML 1.0 Trait

queryParameters:
  foo: string
```

base.raml
```yaml
#%RAML 1.0

title: base

types:
  mystring: string

traits:
  foo: !include trait.raml
```

api.raml
```yaml
#%RAML 1.0 Extension

extends: ./base.raml

title: foo

types:
  mytype: string

/foobar:
  get:
    is: [foo]
```

index.js
```javascript
let raml = require('raml-1-parser');

function print(json) {
  console.log(JSON.stringify(json, null, 2));
}

raml.loadApi('./api.raml')
  .then(ast => {
    return ast.expand();
  })
  .then(ast => {
    print(ast.errors());
    print(ast.toJSON({ serializeMetadata: false }));
  })
  .catch(err => setImmediate(() => { throw err }));
```

Running this will fail to expand the 'foo' trait. It also displays some errors which are not correct, like `Missing required property 'title'` in `base.raml`. And `Unrecognized trait: 'foo'.` in `api.raml`.

If I make the trait local to base.raml, it expands fine. Or if I remove the types definition from base.raml, it will happily render the included trait..
