### ISSUE TITLE
facet 'multipleOf' must be greater than zero

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#660]
RAML:

```yaml
#%RAML 1.0
title: Integer with invalid multipleOf
types:
  TestType:
    type: number
    multipleOf: 0
```

should be invalid with the following message:

> 'multipleOf' must be greater than zero.

This is related to: https://github.com/raml-org/raml-java-parser/issues/344
