### ISSUE TITLE
[Question/Bug?] How to get the library of origin of a resourceType ?

### ISSUE THREAD

**Issue by JonathanMontane** [raml-org/raml-js-parser-2#695]
If I have a `Library` that defines `resourceTypes`, the resourceTypes of the library get included into the resourceTypes of the `Api`, but without the name of the library as defined in the `uses` field.

e.g. for the following files
```yaml
#%RAML 1.0 Library
# library.raml
resourceTypes:
  collection:
    ...
```
and
```yaml
#%RAML 1.0
# input.raml
uses:
  Api: library.raml
/test
  type: 'Api.collection'
```

we get the following behavior:
```js
const test = raml.loadApiSync('./input.raml') // same behavior with `attributeDefaults: false`
assert(test.resources()[0].type().name() === 'Api.collection', true)
assert(test.resourceTypes()[0].name() === 'collection', true)
```

As you can see, there is a mismatch between the names. So how can I get the name of the containing library for the resourceType, if it is contained ? I tried using `meta`, `kind`, `parent`. With `meta`, I can tell that it was imported from a Library (if I set `attributeDefaults` to `false`), but I can't tell which Library it comes from.

Note that if I have multiple Libraries that define the same resourceType internally (e.g. `collection` in `Lib1` and in `Lib2`), I end up with an array of resourceTypes with the same name, which would creates collisions when trying to create a RAML File.
