### ISSUE TITLE
Null collections are serialized to JSON in a strange way

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#703]
`null` collections are transformed to one element JOSN collections with `null` or `"null"` value.

For example, the following RAML spec
```yaml
#%RAML 1.0
title: test

types:
  StringType1:
    enum:
  StringType2:
    enum: null

/test:
  is: 
```
is serialized to JSON as (with unnecessary elements removed manually):
```json
{
    "types": [
      {
        "StringType1": {
          "name": "StringType1",
          "type": [
            "string"
          ],
          "enum": [
            null
          ]
        }
      },
      {
        "StringType2": {
          "name": "StringType2",
          "type": [
            "string"
          ],
          "enum": [
            "null"
          ]
        }
      }
    ],
    "title": "test",
    "resources": [
      {
        "is": [
          null
        ],
        "relativeUri": "/test"
      }
    ]
  }
```

I think, in JSON we should have `"enum": []` and `"is": []`, or `"enum": null` and `"is": null`.

**Comment by sichvoge** [comment]
The question is if you can have something like:

```yaml
#%RAML 1.0
title: test

types:
  StringType1:
    enum:
  StringType2:
    enum: [ null, "test" ]

/test:
  is:
```

What does `enum: null` even mean?
