### ISSUE TITLE
Default value against enum validation failure for RAML 0.8

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#717]
For
```
#%RAML 0.8
title: test API

/track:
  get:
    queryParameters:
      user_ip_address:
        enum: [ a ]
        default: a

```
an invalid error is reported:
```
value should be one of: 'a'at line 9 col 9
```

in RAML 1.0 it works fine
