### ISSUE TITLE
Enum elements does not respect its types

### ISSUE THREAD

**Issue by carowright** [raml-org/raml-js-parser-2#719]
Consider this raml file:

```
#%RAML 1.0
title: Candidate
version: 1.0
mediaType: application/json

/Candidates:
  get:
    queryParameters:
      sourceSelection:
        description: description
        enum: [1,2,3,4,5]
        type:  number
        required: true
        example: 5
 ```

And this is a part of the result of the parser:
```
{
  "name": "sourceSelection",
  "displayName": "sourceSelection",
  "typePropertyKind": "TYPE_EXPRESSION",
  "type": [
    "number"
  ],
  "example": 5,
  "required": true,
  "description": "description",
  "enum": [
    "1",
    "2",
    "3",
    "4",
    "5"
  ],
  "structuredExample": {
    "value": "5",
    "strict": true,
    "name": null,
    "structuredValue": 5
  }
}
```

The values inside enum property are strings instead of numbers.
