### ISSUE TITLE
The parser does not regard as string a value bounded by angle braces

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#721]
For example, for the following spec
```
#%RAML 0.8
title: test API
/inputs:
  post:
    headers:
      Authorization:
        default: <token>
```
an error is throw: "String is expaected"
