### ISSUE TITLE
Some annotation types are missing after expanding a single library

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#737]
For example, consider a libraryt mainLib.raml:
```
#%RAML 1.0 Library

uses:
  lib: ./lib.raml

resoureTypes;
  resourceType:
    type: lib.rt
```
where lb. rt is
```
#%RAML 1.0 Library

annotationTypes:
  at:

resoureTypes;
  rt:
    type:
      rt1:
        param1: at
  rt1:
    (<<param1>>): stringValue
```

The expanded mainLib.raml must contain the lib.at annotation type, but it does not.
