### ISSUE TITLE
Parser fails to process a cyclic dependency between data type fargment and library

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#739]
Suppose, we have lib.raml library spec
```
#%RAML 1.0 Library

types:
  workItem: !include workItem.raml
```
and workItem.raml type fragment:
```
#%RAML 1.0 DataType

uses:
  lib: lib.raml

type: object
properties:
  workItmes:
    type: lib.workItem[]
```

In the JSON representation of **expanded** lib.raml the the `workItems` appears to have `lib.workItem` as component type (at the same time, no library is available under `lib` namespace)
