### ISSUE TITLE
Properties of object union type are missing in JSON

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#743]
For example, let's define `T3` as a union of two object types:
```
types:
  T1: object
  T2: object
  T3:
    type: T1|T2
    properties:
      prop: 
```
than its properties are not serialized to JOSN:
```
{
        "T3": {
          "name": "T3",
          "displayName": "T3",
          "type": [
            "T1|T2"
          ]
        }
      }
```
