### ISSUE TITLE
securedBy defined at top level of extension does not appear in method enhancements

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#745]
extension.raml:

```
#%RAML 1.0 Extension
extends: api.raml

securitySchemes:
  oauth2_0: !include ./oauth2_0.raml

securedBy: oauth2_0
```

api.raml:

```
#%RAML 1.0
title: Test API

/resource:
  post:
    body:
      application/json:

```

Result: while parser JSON output for extension has `securedBy: oauth2_0`, `post` method does not.

**Comment by ddenisenko** [comment]
extension.raml:

```
#%RAML 1.0 Extension
extends: api.raml

securitySchemes:
  oauth2_0: !include ./oauth2_0.raml

securedBy: oauth2_0
```

api.raml:

```
#%RAML 1.0
title: Test API

/resource:
  post:
    body:
      application/json:

```

Result: while parser JSON output for extension has `securedBy: oauth2_0`, `post` method does not.
