### ISSUE TITLE
includes might not be resolved correctly

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#753]
Let's assume I have the following structure:

```
./resourceTypes/collection.raml
./examples/example.raml
./api.raml
```

**./resourceTypes/collection.raml**

```yaml
#%RAML 1.0 ResourceType

post:
  body: 
    application/json:
      example: <<postRequestBodyExample>>
```

**./examples/example.raml**

```yaml
#%RAML 1.0 NamedExample

subscriptionID: 8f19cb50-3f57-4d38
name: NewSub
description: This is the new subscription.
startDate: 2015-01-01
endDate: 2018-01-01
quantity: 5
productName: ABC Product
supportLevel: 4
```

**./api.raml**

```yaml
#%RAML 1.0
title: A title

resourceTypes: 
  collection: !include resourceTypes/collection.raml

/testURI:
  type:
    collection:
      postRequestBodyExample: !include examples/example.raml
```

The parser tells me that there is the following problem `cannot set property 'path' of unknown`. Moving out `collection.raml` into the root directory

```
./collection.raml
./examples/example.raml
./api.raml
```

and changing the path inside `api.raml`, everything works fine again. What also works is to leave `collection.raml` inside the resource types folder and change the path for the example include from `examples/example.raml` to `../examples/example.raml`.

This seems to be rather strange, to be honest. When do we resolve the `includes`? It seems to me that they are not resolved before we start resolving parameters, etc. If we would resolve includes on YAML level, we should only parse the following:

```yaml
#%RAML 1.0
title: A title

resourceTypes: 
  collection: 
    post:
      body: 
        application/json:
          example: <<postRequestBodyExample>>

/testURI:
  type:
    collection:
      postRequestBodyExample: 
        subscriptionID: 8f19cb50-3f57-4d38
        name: NewSub
        description: This is the new subscription.
        startDate: 2015-01-01
        endDate: 2018-01-01
        quantity: 5
        productName: ABC Product
        supportLevel: 4
```

What do I miss?
