### ISSUE TITLE
Issue with overlays, default media type, and resource type fragments

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#757]
Hi, I have the following RAML files:

**collection.raml**
```yaml
#%RAML 1.0 ResourceType
post:
  description: Add a new <<resourcePathName | !singularize>>
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>
```

**localize.raml**
```yaml
#%RAML 1.0 Overlay
usage: Spanish localization
extends: master.raml

/customers:
  get:
    description: Recuperar una lista de clientes
  post:
    description: Agregue un nuevo cliente
```

**master.raml**
```yaml
#%RAML 1.0
title: ACME Banking API
version: 1.0
mediaType: application/json

resourceTypes: 
  collection: !include collection.raml
      
types:
  Customer:

/customers:
  type: collection
  get:
    description: Retrieve a list of customers
```

All are in the same directory.

The **master.raml** file is valid, but when I validate the overlay **localize.raml** I get the following error: "invalid media type at line 5 col 4 in collection.raml"

I would expect that I don't get any validation error.

Putting `application/json` after the body node inside **collection.raml** will fix this error. Obviously, something is wrong.
