### ISSUE TITLE
Incorrect call to fsResolver.content method when contentAsync is defined

### ISSUE THREAD

**Issue by agustinlg** [raml-org/raml-js-parser-2#765]
Having an INCORRECT RAML:
```
#%RAML 1.0
title: asdfasdfdjdjdjdjdjdhjdhdkaaasd
 
uses:
  types:
    some: other.raml
```

And calling the parser through loadApi(), then expand(true), then toJson(). With custom fsResolver:
```
fsResolver: {
  contentAsync: onFileRequest,
  content: path => {
    throw new Error('RamlParser should call contentAsync instead of content. File: ' + path)
  }
}
```

The `fsResolver.content` method gets called with path `/[object Object]`.
The method should not be called since the fsResolver.asyncContent is defined.
