### ISSUE TITLE
Error message for type related annotations should be more clear

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#768]
Assume the following example:

```yaml
#%RAML 1.0 Library

types:
  test:
    (oas-schema-title): human
    properties:
      (oas-schema-title): human
      node:
        (oas-schema-title): human
        type: string

annotationTypes:
  oas-schema-title: 
    type: string
    allowedTargets: TypeDeclaration
```

The parser returns an error for the second use of `(oas-schema-title)` right under `properties` which states the following: `Property '(oas-schema-title)' refers to unknown type 'human'`.

What I would expect is that the parser tells me that I am not allowed to use the annotations inside the `properties` node. Right?

**Comment by KonstantinSviridov** [comment]
Hi, Christian

In fact, the spec does not prohibit us from using bracket symbols in property names. Thus, what the parser sees, is property named "(oas-schema-title)" refering unknown type named "human". 

But we can modify existing error messages for those properties which have their names put into brackets. Instead of just
```
Property '(oas-schema-title)' refers to unknown type 'human'
```
we can produce
```
Invalid attempt to use 'oas-schema-title' annotation under the 'properties' key or property '(oas-schema-title)' refers to unknown type 'human'
```

But even in such case we will not catch case when type "human" is defined:
```
#%RAML 1.0 Library

types:
  human:
  test:
    (oas-schema-title): human
    properties:
      (oas-schema-title): human
      node:
        (oas-schema-title): human
        type: string

annotationTypes:
  oas-schema-title: 
    type: string
    allowedTargets: TypeDeclaration
```
