### ISSUE TITLE
Version 1.1.28: Error parsing facets "Built in facet 'format' can not be overriden"

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#776]
Raml File:
```
#%RAML 1.0
title: type example
version: 1

types:
 ResourceLink:
   description: a description
   facets:
     a: string
     b: number
   properties:
     href: string
     rel:
       enum: [self, next, prev]
     method:
       default: get
       required: false
 ImageLink:
   properties:
     href: string
     rel:
       enum: [SmallImage, MediumImage, LargeImage]
```

Error:
```
{
  "parserErrors": [
    {
      "code": "OVERRIDE_BUILTIN_FACET",
      "message": "Built in facet 'format' can not be overriden",
      "path": "func-spec-example-1.yaml",
      "range": {
        "start": {
          "line": 9,
          "column": 5,
          "position": 126
        },
        "end": {
          "line": 9,
          "column": 6,
          "position": 127
        }
      },
      "isWarning": false
    }
  ]
}
```

Parser usage:
```
const options = {
  "attributeDefaults": false,
  "rejectOnErrors": true,
  "validate": true,
  "noExtension": true,
  "format": "yaml"
}

const jsonOptions = {
  "serializeMetadata": false
}

parser.loadApi(filePath, options).expand(true).toJSON(jsonOptions)
```
