### ISSUE TITLE
Properties from included DataType (as a base type) overrides properties from current DataType

### ISSUE THREAD

**Issue by jarrodek** [raml-org/raml-js-parser-2#777]
For the following files:

**file.raml**

```yaml
#%RAML 1.0 DataType

displayName: File
description: The File resource type.
type: !include resource.raml

properties:
  thumbnail:
    type: !include thumbnail.raml
    required: false
```

**resource.rml**

``` yaml
#%RAML 1.0 DataType

displayName: Resource
description: A reference to a file's parent.
type: object

properties:
  kind:
    type: string
    required: false
    description: This is always drive#parentReference.
    enum: [drive#parentReference]
    default: drive#parentReference
  id:
    type: string
    description: The ID of the parent
    required: false
  selfLink:
    type: string
    description: A link back to this reference
    required: false
```

**thumbnail.rml**

``` yaml
#%RAML 1.0 DataType

displayName: Thumbnail
description: Thumbnail for the file.

properties:
  image:
    type: string
    required: false
    description: The URL-safe Base64 encoded bytes of the thumbnail image. It should conform to RFC 4648 section 5.
  mimeType:
    type: string
    required: false
    description: The MIME type of the thumbnail.
```

the `toJson()` function called on result of parsing `file.raml` file is as follows:

```json
{
  "displayName": "File",
  "typePropertyKind": "INPLACE",
  "required": true,
  "description": "The File resource type.",
  "type": {
    "name": "type",
    "displayName": "Resource",
    "typePropertyKind": "TYPE_EXPRESSION",
    "type": "object",
    "description": "A reference to a file's parent.",
    "properties": [
      {
        "name": "kind",
        "displayName": "kind",
        "typePropertyKind": "TYPE_EXPRESSION",
        "type": "string",
        "default": "drive#parentReference",
        "required": false,
        "description": "This is always drive#parentReference.",
        "enum": [
          "drive#parentReference"
        ],
        "key": "kind"
      },
      {
        "name": "id",
        "displayName": "id",
        "typePropertyKind": "TYPE_EXPRESSION",
        "type": "string",
        "required": false,
        "description": "The ID of the parent",
        "key": "id"
      }
    ]
  }
}
```

It is missing properties defined in the `file.raml` and only produces JavaScript object for properties inherited in `type: !include resource.raml` directive. Rest of it is omitted and never gets to the output. Expected behavior is combination of properties of both `resouce.raml` and `file.raml`. 

The `toJson()` function is called with following options:

```json
{
  dumpSchemaContents: false,
  rootNodeDetails: true,
  serializeMetadata: false
}
```
I've tried changing the parameters but with the same result.
