### ISSUE TITLE
Extension do not extend `baseUri` properly

### ISSUE THREAD

**Issue by jarrodek** [raml-org/raml-js-parser-2#779]
Raml A:
```yaml
#%RAML 1.0
title: Test
baseUri: http://domain.org
/resource:
  get:
```

Raml B:
```yaml
#%RAML 1.0 Extension
extends: test.raml
baseUri: http://devx.example.com
```

When parsing B it inherits `baseUri` properly from the extension but on a resource level the `absoluteUri` property contains `http://domain.org` base URI. When you remove `baseUri: http://domain.org` from A then resource's `absoluteUri` equals `relativeUri`.
This is related to JSON output but the AST gives the same output when calling:
```
// result = AST
r = result.resources()[0];
r.absoluteUri();
// prints "http://domain.org/resource"
```

and it should print `http://devx.example.com/resource`.
