### ISSUE TITLE
Doubt about annotation

### ISSUE THREAD

**Issue by biaggi** [raml-org/raml-js-parser-2#780]
I have a field in a resource defined this way: 

        accountId:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          required: false
          description: |
            Account identifier.

And the mentioned annotations is defined this way:

```
#%RAML 1.0 AnnotationTypeDeclaration
displayName: BindingDefinition
description: This annotation describes the binding definition in a method and input/output on a resource
usage: This annotation should be used in properties in data types indicating the binding definition
type: array
items:
  properties:
    method:
      type: string
      required: true
      description: This field defines to which method the binding applies
      enum: [GET, PATCH, POST, PUT, DELETE]
    input:
      type: string
      required: true
      description: The binding related to the field when used as an input
      enum: [OPTIONAL, REQUIRED, NONE]
    output:
      type: string
      required: true
      description: The binding related to the field when used as an output
      enum: [OPTIONAL, REQUIRED, NONE]
```

As you can see the field output is setting output to required, but the output for the field as json is returning required as false. 

I've been reading annotations documentation but still I'm confused if this required field should be true or false

Is this behavior raml compliant? or the json output should be true for the required key for that property...

Regards
