### ISSUE TITLE
XML type requires a <body> tag as root element that should not

### ISSUE THREAD

**Issue by agustinlg** [raml-org/raml-js-parser-2#781]
Using a RAML type to define a type for both XML and JSON inputs fails in API Designer because it seems to expect the XML to use a <body> root element when it should not.

Comment the  line:
`inputExample: !include examples/TestObject/post/inputwithoutbody.xml `
and un-coment the line:
`#inputExample: !include examples/TestObject/post/input.json`
Verify that the error is gone

[case00163919-v2.0.zip](https://github.com/raml-org/raml-js-parser-2/files/1206426/case00163919-v2.0.zip)

**Comment by KonstantinSviridov** [comment]
Hi, Agustin!

> it fails because it seems to expect the XML to use a root element when it should not.

Do you mean, there are some cases when no root element should be used? What are these cases?

I would say, there always must be some root element because adding a property must be reflected in adding an element on the same hierarchy level.

As one is not allowed to have several root elements, the following XML
```
<?xml version="1.0"?>
<batch>
  <action>AR</action>
</batch>
<extra_property>
</extra_property>

```
is invalid. Thus, you need some root element.


As for the root element name, the current implementation requires it to be equal to the type name (it is "Request" in your case), and this logic is broken for cases of default media type usage.

Our proposition is to cancel this requirement and to start accepting all names for root elements.

**Comment by iamerico** [comment]
Hi @KonstantinSviridov, the proposal to accept all names for root elements seems good. Does the closing of this issue means this change was introduced added?

**Comment by KonstantinSviridov** [comment]
Hi @iamerico . That's right. From now we accept all names for root tags.

**Comment by iamerico** [comment]
Hi @KonstantinSviridov , I'm having the same problem.
I must be able to support this format (_cancel-order.xml_):
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<UpdateRequestOfWorkOrder>
  <ExecutionContext>
    <UserId>SamsungAPI</UserId>
    <Password>Samsung062017</Password>
    <DateFormat>20170826T010203.800Z</DateFormat>
  </ExecutionContext>
  <Entity>
    <AlternateIdentifiers>
      <WorkOrderAlternateIdentifier>
        <Type>
          <Abbreviation>ReferenceNumber</Abbreviation>
        </Type>
        <Value>8391481342</Value>
      </WorkOrderAlternateIdentifier>
    </AlternateIdentifiers>
  </Entity>
</UpdateRequestOfWorkOrder>
```

Here’s the DataType (_cancel-order-datatype.raml_):
```
#%RAML 1.0 DataType
properties:
  ExecutionContext:
    properties:
      UserId: string
      Password: string
      DateFormat: string
  Entity:
    properties:
      AlternateIdentifiers:
        properties:
          WorkOrderAlternateIdentifier:
             properties:
              Type:
                properties:
                  Abbreviation: string
              Value: string
```

Here’s my RAML:
```
#%RAML 1.0
title: XPO API
version: v1
mediaType: [application/xml]
baseUri: https://sta-desktop.xpolastmile.com/api/xpo/xml

types:
  UpdateRequestOfWorkOrder: !include cancel-order-datatype.raml

/CancelWorkOrder:
  post:
    body:
      type: UpdateRequestOfWorkOrder
      example: !include cancel-order.xml
```

**Error:**
> The validation error in my RAML view is `Unexpected root node "UpdateRequestOfWorkOrder", "body" is expected.`

I'm failing on some definition.
