### ISSUE TITLE
Unrecognized security scheme error

### ISSUE THREAD

**Issue by DataGreed** [raml-org/raml-js-parser-2#785]
Whenever I try to render a raml api file with custom security scheme, I get a strange error.

Here's the file api.raml:

```
#%RAML 1.0
title: Some API
version: v1
mediaType:  application/json
baseUri: https://example.com/api/v1/

securitySchemes:
  hmac: !include securitySchemes/hmac.raml
```

here's `securitySchemes/hmac.raml`:

```
#%RAML 1.0 AbstractSecurityScheme
type: x-hmac
describedBy:
  headers:
    Authorization:
      description: Some description
      type: string
      example: Authorization hmac a98y23awdd0aw9
```

The error I get is:
```
{
    "code": "UNRECOGNIZED_ELEMENT",
    "message": "Unrecognized security scheme: 'hmac'.",
    "path": "api.raml",
    "range": {
      "start": {
        "line": 551,
        "column": 16,
        "position": 14935
      },
      "end": {
        "line": 551,
        "column": 20,
        "position": 14939
      }
    }
```

Which is quite strange, especially because the previous parser versions were ok with this markup and raml2obj works just fine with it.
