### ISSUE TITLE
Error when parsing RAML type examples

### ISSUE THREAD

**Issue by DataGreed** [raml-org/raml-js-parser-2#786]
Parser does not seem to know that the examples can be provided as objects.

In the RAML spec (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md) there is an example of giving examples for types:

```
types:
  Email:
    type: object
    properties:
      subject: string
      body: string
  Emails:
    type: Email[]
    minItems: 1
    uniqueItems: true
    example: # example that contains array
      - # start item 1
        subject: My Email 1
        body: This is the text for email 1.
      - # start item 2
        subject: My Email 2
        body: This is the text for email 2. 
```

Whenever I implement an example like this one, I get the following errors from the parser:

```
{
    "code": "TYPE_EXPECTED",
    "message": "string is expected",
    "path": "types/general.raml",
    "range": {
      "start": {
        "line": 2928,
        "column": 4,
        "position": 58920
      },
      "end": {
        "line": 2928,
        "column": 6,
        "position": 58922
      }
    }
```
