### ISSUE TITLE
Invalid JSON schema: Reference could not be resolved

### ISSUE THREAD

**Issue by iamerico** [raml-org/raml-js-parser-2#790]
When reference to the following a json schema (**company-schema.json**):
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "company-schema.json",
	"type": "object",
	"title": "A legal company (legal person)",
	"allOf":
	[
		{
			"$ref": "partner-schema.json"
		},
		{
			"properties":
			{
				"type":
				{
					"type": "string",
					"enum":
					[
						"AG",
						"GmbH"
					],
					"description": "Legal status"
				}
			},
			"required":
			[
				"type"
			]
		}
	]
}
```
**partner-schema.json:**
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "partner-schema.json",
	"type": "object",
	"title": "Base for company and person",
	"properties":
	{
		"name":
		{
			"type": "string",
			"description": "Second name or company name"
		},
		"active":
		{
			"type": "boolean",
			"description": "Still doing business with him/it?"
		}
	},
	"required":
	[
		"name",
		"active"
	]
}
```

It is shown as faulty (**api.raml**):
```
#%RAML 1.0
title: Data type demo. Nothing really useful
baseUri: http://localhost:8080/api/

/json-schema:
  /partners:
      post:
        body:
          application/json:
            type: !include ref/company-schema.json
```

**Message error:**
> type:Invalid JSON schema: Reference could not be resolved: company-schema.json#partner-schema.json
