### ISSUE TITLE
Incorrect implementation of RAML 1.0 and OAuth 2.0 scopes

### ISSUE THREAD

**Issue by RTARDA** [raml-org/raml-js-parser-2#793]
It seems that the RAML 1.0 OAuth 2.0 securityScheme is required to supply the list of allowable scopes that can later be required by an overriding resource/method securedBy scope list.
If a scope in the resource's securedBy is not present in the securityScheme declaration then the APIkit console throws this error: "[error] The 'openid' scope is not allowed for the 'oauth_2_0' security scheme. Allowed scopes are: ." for example, when my securityScheme declaration omits a settings/scope.
This appears to be in conflict with the RAML 1.0 spec which allows the scopes in the root-level secureityScheme to be overridden by the resource/method-level securedBy.

Java Parser validates just OK   
<img width="1068" alt="java parser validates ok" src="https://user-images.githubusercontent.com/20116404/30377865-bc911374-9867-11e7-98e2-b06f0e229f69.png">

But JS parser shows errors:
<img width="1063" alt="js parser shows errors" src="https://user-images.githubusercontent.com/20116404/30377877-c400698e-9867-11e7-9894-b945e699106e.png">

API Console shows same errors:
<img width="1022" alt="api console shows same errors" src="https://user-images.githubusercontent.com/20116404/30377885-caed0d2e-9867-11e7-9f16-71849eab7b6f.png">

**Comment by RTARDA** [comment]
[SE-6494.zip](https://github.com/raml-org/raml-js-parser-2/files/1299412/SE-6494.zip)

**Comment by KonstantinSviridov** [comment]
Hi, @RTARDA !

Overriding top-level securedBy in resource/method level means that any RAML tooling must understand the resource/method as secured by schema(s) specified in its own `securedBy` value rather then by those specifiend in the top level `securedBy` value.

In any case each scope specified in `securedBy` must belong to a list of available scopes. Thus, it is not required to supply the whole list of available scopes as `scopes` parameter value in `securedBy` (it would be rather senseless), but each scope supplied must belong to the list of available scopes.

The behavior observed is natural as the parser sees a bunch of scopes none of which belongs to the list of available scopes.

Regards,
Konstantin

**Comment by RTARDA** [comment]
In the attached example, each scope supplied does belong to the list of available scopes.
As you can see in the "get"
```  get:
    securedBy:
      - oauth_2_0: { scopes: [ openid, auth-columbia, auth-facebook, auth-google, writemine, writeany ] }
```
the scopes supplied belong to the ```oauth_2_0``` securitySchemes provided:
```  scopes: [ openid, auth-columbia, auth-facebook, auth-google, auth-linkedin, auth-twitter, auth-windowslive, readmine, readany, writemine, writeany ]
```

**Comment by KonstantinSviridov** [comment]
In fact, in your example all the available scopes are commented away, and I was thinking, it had been done on purpose.
```yaml
settings:
  authorizationUri: https://oauth.cc.columbia.edu/as/authorization.oauth2
  accessTokenUri: https://oauth.cc.columbia.edu/as/token.oauth2
  authorizationGrants: 
    - authorization_code
#  scopes: [ openid, auth-columbia, auth-facebook, auth-google, auth-linkedin, auth-twitter, auth-windowslive, readmine, readany, writemine, writeany ]
```
After inseting the missing line break into the last code block in your message and seeng the complete list I start thinking that you forgot about this comment.

Uncommenting the scopes does fix the issue.
