### ISSUE TITLE
Can't get name of ResourceTypeRef

### ISSUE THREAD

**Issue by picsoung** [raml-org/raml-js-parser-2#80]
Thanks for this tool!

I have a spec like this

```
resourceTypes:
  - collection:
      get:
         ...

/users:
  type:
    collection:
      exampleCollection: !include examples/users.json
      exampleItem: !include examples/user.json
      resource: place
```

I loading the api using `var api = raml.loadApiSync(path)`
I get the different resourceTypes with `api.resourceTypes()`

But know I want to iterate over my resources, and find what is the type of each resource, so I can then have access to methods defined in the corresponding type.

basically I want to retrieve `collection` when I am on resource `/users`.
I have tried `resource.type().kind()` `resource.type().value()` without success.

Thanks for the help
Best
