### ISSUE TITLE
Circular JSON schema files

### ISSUE THREAD

**Issue by sorohan** [raml-org/raml-js-parser-2#809]
I have the following RAML & schema files:

api.raml:

```
#%RAML 1.0
---
title: Testing Circular Schema Files
version: v2
baseUri: "{version}"
types:
  CircularType:
    type: !include schemas/one.json

/foos:
  post:
    body:
      application/json:
        type: CircularType
```

schemas/one.json:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "definitions": {
    "oneDef": {
      "type": "string"
    }
  },
  "properties": {
    "a": {
      "$ref": "./two.json"
    }
  }
}
```

schemas/two.json:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "properties": {
    "b": {
      "$ref": "./one.json#/definitions/oneDef"
    }
  }
}
```

When parsing this RAML it is throwing an error CIRCULAR_REFS_IN_JSON_SCHEMA.

Is this expected behaviour? I believe it's valid for json schema files to have circular references. Even the schemas themselves in this case aren't circular, only the files are.

The object described by these schemas is a simple object:

```json
{
  "a": {
    "b": "some string"
  }
}
```

This is the code I'm using to parse the RAML:

```javascript
const ramlParser = require('raml-1-parser');
ramlParser.load('./api.raml')
  .then(result => {
    if (result.errors) {
      console.log(result.errors);
    } else {
      console.log('success parsing raml');
    }
  });
```

I've created this repo to demonstrate the issue: https://github.com/sorohan/circular-schema-files
