### ISSUE TITLE
Type inheritance in reponses not working for parameters

### ISSUE THREAD

**Issue by DataGreed** [raml-org/raml-js-parser-2#832]
I've got custom type parameter with properties. The type is defined in an external file and is included. Here's the type:

```
timeMetaObject:
  type: object
  properties:
    time:
      type: number
      description: Current time, unixtimestamp
  example:
    time: 1504185635.665978
```

For some reason the `properties` for this parameter does not exist.
How do I render `time` for this node? How do I access any child properties?
