### ISSUE TITLE
formParameters must be object, not array

### ISSUE THREAD

**Issue by xaka** [raml-org/raml-js-parser-2#86]
RAML:

```
#%RAML 0.8
---
title: Example API
baseUri: http://example.com
/resource:
  /{resourceId}:
    post:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            name:
              description: The name of the resource to create
              type: string
              example: Comment
            description:
              description: A description of the resource to create
              type: string
              example: User-generated content pertinent to the associated blog post
```

RAML 0.8 JSON:

```
                "multipart/form-data": {
                  "formParameters": {
                    "description": {
                      "description": "A description of the resource to create",
                      "displayName": "description",
                      "example": "User-generated content pertinent to the associated blog post",
                      "type": "string"
                    },
                    "name": {
                      "description": "The name of the resource to create",
                      "displayName": "name",
                      "example": "Comment",
                      "type": "string"
                    }
                  }
                }
```

RAML 1.0 JSON:

```
                "multipart/form-data": {
                  "formParameters": [
                    {
                      "description": "The name of the resource to create",
                      "displayName": "name",
                      "example": "Comment",
                      "name": "name",
                      "repeat": false,
                      "required": false,
                      "type": "string"
                    },
                    {
                      "description": "A description of the resource to create",
                      "displayName": "description",
                      "example": "User-generated content pertinent to the associated blog post",
                      "name": "description",
                      "repeat": false,
                      "required": false,
                      "type": "string"
                    }
                  ],
                  "name": "multipart/form-data"
                }
```

P.S. It also worths to mention that `formParameters` format isn't consistent with `uriParameters` and `queryParameters`.
