### ISSUE TITLE
Quotes around keys not supported?

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#95]
I'm currently building a model which has properties containing colons, it seems there is no way to escape these.

```yaml
    "channel:links:allowed":
        type: boolean
        description: Specified whether links are allowed in the chat.
```
